/*
 * FontAwesome.c
 *
 * PROJEKT: PKS-EDIT for Windows
 *
 * purpose: simplify usage of FontAwesome icons in PKS-Edit.
 *
 * 										created:
 * 										last modified:
 *										author: Tom
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#include <Windows.h>
#include <string.h>
#include "fontawesome.h"
#include "hashmap.h"

typedef struct tagFA_ICON_NAME {
	const char* fa_name;
	wchar_t fa_code;
	int fa_regular_available;
} FA_ICON_NAME;

static FA_ICON_NAME _faIcons[] = {
{ "fa-glass",  L'\uf000' },
{ "fa-music",  L'\uf001' },
{ "fa-search",  L'\uf002' },
{ "fa-envelope-o",  L'\uf003' },
{ "fa-heart",  L'\uf004',1 },
{ "fa-star",  L'\uf005', 1 },
{ "fa-star-o",  L'\uf006' },
{ "fa-user",  L'\uf007', 1 },
{ "fa-film",  L'\uf008' },
{ "fa-th-large",  L'\uf009' },
{ "fa-th",  L'\uf00a' },
{ "fa-th-list",  L'\uf00b' },
{ "fa-check",  L'\uf00c' },
{ "fa-remove",  L'\uf00d' },
{ "fa-close",  L'\uf00d' },
{ "fa-times",  L'\uf00d' },
{ "fa-search-plus",  L'\uf00e' },
{ "fa-search-minus",  L'\uf010' },
{ "fa-power-off",  L'\uf011' },
{ "fa-signal",  L'\uf012' },
{ "fa-gear",  L'\uf013' },
{ "fa-cog",  L'\uf013' },
{ "fa-trash-o",  L'\uf014' },
{ "fa-trash-can",  L'\uf2ed', 1 },
{ "fa-home",  L'\uf015' },
{ "fa-file-o",  L'\uf016' },
{ "fa-clock-o",  L'\uf017' },
{ "fa-road",  L'\uf018' },
{ "fa-download",  L'\uf019' },
{ "fa-arrow-circle-o-down",  L'\uf01a' },
{ "fa-arrow-circle-o-up",  L'\uf01b' },
{ "fa-inbox",  L'\uf01c' },
{ "fa-play-circle-o",  L'\uf01d' },
{ "fa-rotate-right",  L'\uf01e' },
{ "fa-repeat",  L'\uf01e' },
{ "fa-refresh",  L'\uf021' },
{ "fa-list-alt",  L'\uf022' },
{ "fa-lock",  L'\uf023' },
{ "fa-flag",  L'\uf024' },
{ "fa-headphones",  L'\uf025' },
{ "fa-volume-off",  L'\uf026' },
{ "fa-volume-down",  L'\uf027' },
{ "fa-volume-up",  L'\uf028' },
{ "fa-qrcode",  L'\uf029' },
{ "fa-barcode",  L'\uf02a' },
{ "fa-tag",  L'\uf02b' },
{ "fa-tags",  L'\uf02c' },
{ "fa-book",  L'\uf02d' },
{ "fa-bookmark",  L'\uf02e' },
{ "fa-print",  L'\uf02f' },
{ "fa-camera",  L'\uf030' },
{ "fa-font",  L'\uf031' },
{ "fa-bold",  L'\uf032' },
{ "fa-italic",  L'\uf033' },
{ "fa-text-height",  L'\uf034' },
{ "fa-text-width",  L'\uf035' },
{ "fa-align-left",  L'\uf036' },
{ "fa-align-center",  L'\uf037' },
{ "fa-align-right",  L'\uf038' },
{ "fa-align-justify",  L'\uf039' },
{ "fa-list",  L'\uf03a' },
{ "fa-dedent",  L'\uf03b' },
{ "fa-outdent",  L'\uf03b' },
{ "fa-indent",  L'\uf03c' },
{ "fa-video-camera",  L'\uf03d' },
{ "fa-photo",  L'\uf03e' },
{ "fa-image",  L'\uf03e', 1 },
{ "fa-picture-o",  L'\uf03e' },
{ "fa-pencil",  L'\uf040' },
{ "fa-map-marker",  L'\uf041' },
{ "fa-adjust",  L'\uf042' },
{ "fa-tint",  L'\uf043' },
{ "fa-edit",  L'\uf044' },
{ "fa-pencil-square-o",  L'\uf044' },
{ "fa-share-square-o",  L'\uf045' },
{ "fa-check-square-o",  L'\uf046' },
{ "fa-arrows",  L'\uf047' },
{ "fa-step-backward",  L'\uf048' },
{ "fa-st-backward",  L'\uf049' },
{ "fa-backward",  L'\uf04a' },
{ "fa-play",  L'\uf04b' },
{ "fa-pause",  L'\uf04c' },
{ "fa-stop",  L'\uf04d' },
{ "fa-forward",  L'\uf04e' },
{ "fa-st-forward",  L'\uf050' },
{ "fa-step-forward",  L'\uf051' },
{ "fa-eject",  L'\uf052' },
{ "fa-chevron-left",  L'\uf053' },
{ "fa-chevron-right",  L'\uf054' },
{ "fa-plus-circle",  L'\uf055' },
{ "fa-minus-circle",  L'\uf056' },
{ "fa-times-circle",  L'\uf057' },
{ "fa-check-circle",  L'\uf058' },
{ "fa-question-circle",  L'\uf059' },
{ "fa-info-circle",  L'\uf05a' },
{ "fa-crosshairs",  L'\uf05b' },
{ "fa-times-circle-o",  L'\uf05c' },
{ "fa-check-circle-o",  L'\uf05d' },
{ "fa-ban",  L'\uf05e' },
{ "fa-arrow-left",  L'\uf060' },
{ "fa-arrow-right",  L'\uf061' },
{ "fa-arrow-up",  L'\uf062' },
{ "fa-arrow-down",  L'\uf063' },
{ "fa-mail-forward",  L'\uf064' },
{ "fa-share",  L'\uf064' },
{ "fa-expand",  L'\uf065' },
{ "fa-compress",  L'\uf066' },
{ "fa-plus",  L'\uf067' },
{ "fa-minus",  L'\uf068' },
{ "fa-asterisk",  L'\uf069' },
{ "fa-exclamation-circle",  L'\uf06a' },
{ "fa-gift",  L'\uf06b' },
{ "fa-leaf",  L'\uf06c' },
{ "fa-fire",  L'\uf06d' },
{ "fa-eye",  L'\uf06e' },
{ "fa-eye-slash",  L'\uf070' },
{ "fa-warning",  L'\uf071' },
{ "fa-exclamation-triangle",  L'\uf071' },
{ "fa-plane",  L'\uf072' },
{ "fa-calendar",  L'\uf073' },
{ "fa-random",  L'\uf074' },
{ "fa-comment",  L'\uf075', 1 },
{ "fa-comment-o",  L'\uf0e5', 1 },
{ "fa-magnet",  L'\uf076' },
{ "fa-chevron-up",  L'\uf077' },
{ "fa-chevron-down",  L'\uf078' },
{ "fa-retweet",  L'\uf079' },
{ "fa-shopping-cart",  L'\uf07a' },
{ "fa-folder",  L'\uf07b', 1 },
{ "fa-folder-open",  L'\uf07c' },
{ "fa-arrows-v",  L'\uf07d' },
{ "fa-arrows-h",  L'\uf07e' },
{ "fa-bar-chart-o",  L'\uf080' },
{ "fa-bar-chart",  L'\uf080' },
{ "fa-twitter-square",  L'\uf081' },
{ "fa-cebook-square",  L'\uf082' },
{ "fa-camera-retro",  L'\uf083' },
{ "fa-key",  L'\uf084' },
{ "fa-gears",  L'\uf085' },
{ "fa-cogs",  L'\uf085' },
{ "fa-comments",  L'\uf086', 1 },
{ "fa-thumbs-o-up",  L'\uf087' },
{ "fa-thumbs-o-down",  L'\uf088' },
{ "fa-star-half",  L'\uf089' },
{ "fa-heart-o",  L'\uf08a' },
{ "fa-sign-out",  L'\uf08b' },
{ "fa-linkedin-square",  L'\uf08c' },
{ "fa-thumb-tack",  L'\uf08d' },
{ "fa-external-link",  L'\uf08e' },
{ "fa-sign-in",  L'\uf090' },
{ "fa-trophy",  L'\uf091' },
{ "fa-github-square",  L'\uf092' },
{ "fa-upload",  L'\uf093' },
{ "fa-lemon-o",  L'\uf094' },
{ "fa-phone",  L'\uf095' },
{ "fa-square-o",  L'\uf096' },
{ "fa-bookmark-o",  L'\uf097' },
{ "fa-phone-square",  L'\uf098' },
{ "fa-twitter",  L'\uf099' },
{ "fa-cebook-f",  L'\uf09a' },
{ "fa-cebook",  L'\uf09a' },
{ "fa-github",  L'\uf09b' },
{ "fa-unlock",  L'\uf09c' },
{ "fa-credit-card",  L'\uf09d' },
{ "fa-feed",  L'\uf09e' },
{ "fa-rss",  L'\uf09e' },
{ "fa-hdd-o",  L'\uf0a0' },
{ "fa-bullhorn",  L'\uf0a1' },
{ "fa-bell",  L'\uf0f3' },
{ "fa-certificate",  L'\uf0a3' },
{ "fa-hand-o-right",  L'\uf0a4' },
{ "fa-hand-o-left",  L'\uf0a5' },
{ "fa-hand-o-up",  L'\uf0a6' },
{ "fa-hand-o-down",  L'\uf0a7' },
{ "fa-arrow-circle-left",  L'\uf0a8' },
{ "fa-arrow-circle-right",  L'\uf0a9' },
{ "fa-arrow-circle-up",  L'\uf0aa' },
{ "fa-arrow-circle-down",  L'\uf0ab' },
{ "fa-globe",  L'\uf0ac' },
{ "fa-wrench",  L'\uf0ad' },
{ "fa-tasks",  L'\uf0ae' },
{ "fa-filter",  L'\uf0b0' },
{ "fa-briefcase",  L'\uf0b1' },
{ "fa-arrows-alt",  L'\uf0b2' },
{ "fa-group",  L'\uf0c0' },
{ "fa-users",  L'\uf0c0' },
{ "fa-chain",  L'\uf0c1' },
{ "fa-link",  L'\uf0c1' },
{ "fa-cloud",  L'\uf0c2' },
{ "fa-flask",  L'\uf0c3' },
{ "fa-cut",  L'\uf0c4' },
{ "fa-scissors",  L'\uf0c4' },
{ "fa-copy",  L'\uf0c5' },
{ "fa-files-o",  L'\uf0c5' },
{ "fa-paperclip",  L'\uf0c6' },
{ "fa-save",  L'\uf0c7' },
{ "fa-floppy-o",  L'\uf0c7', 1 },
{ "fa-square",  L'\uf0c8' },
{ "fa-navicon",  L'\uf0c9' },
{ "fa-reorder",  L'\uf0c9' },
{ "fa-bars",  L'\uf0c9' },
{ "fa-list-ul",  L'\uf0ca' },
{ "fa-list-ol",  L'\uf0cb' },
{ "fa-strikethrough",  L'\uf0cc' },
{ "fa-underline",  L'\uf0cd' },
{ "fa-table",  L'\uf0ce' },
{ "fa-magic",  L'\uf0d0' },
{ "fa-truck",  L'\uf0d1' },
{ "fa-pinterest",  L'\uf0d2' },
{ "fa-pinterest-square",  L'\uf0d3' },
{ "fa-google-plus-square",  L'\uf0d4' },
{ "fa-google-plus",  L'\uf0d5' },
{ "fa-money",  L'\uf0d6' },
{ "fa-caret-down",  L'\uf0d7' },
{ "fa-caret-up",  L'\uf0d8' },
{ "fa-caret-left",  L'\uf0d9' },
{ "fa-caret-right",  L'\uf0da' },
{ "fa-columns",  L'\uf0db' },
{ "fa-unsorted",  L'\uf0dc' },
{ "fa-sort",  L'\uf0dc' },
{ "fa-sort-down",  L'\uf0dd' },
{ "fa-sort-desc",  L'\uf0dd' },
{ "fa-sort-up",  L'\uf0de' },
{ "fa-sort-asc",  L'\uf0de' },
{ "fa-envelope",  L'\uf0e0', 1 },
{ "fa-linkedin",  L'\uf0e1' },
{ "fa-rotate-left",  L'\uf0e2' },
{ "fa-undo",  L'\uf0e2' },
{ "fa-redo",  L'\uf01e' },
{ "fa-legal",  L'\uf0e3' },
{ "fa-gavel",  L'\uf0e3' },
{ "fa-dashboard",  L'\uf0e4' },
{ "fa-tachometer",  L'\uf0e4' },
{ "fa-comments-o",  L'\uf0e6' },
{ "fa-flash",  L'\uf0e7' },
{ "fa-bolt",  L'\uf0e7' },
{ "fa-sitemap",  L'\uf0e8' },
{ "fa-umbrella",  L'\uf0e9' },
{ "fa-paste",  L'\uf0ea' },
{ "fa-clipboard",  L'\uf0ea', 1 },
{ "fa-clipboard-o",  L'\uf328', 1 },
{ "fa-lightbulb-o",  L'\uf0eb' },
{ "fa-exchange",  L'\uf0ec' },
{ "fa-exchange-alt",  L'\uf362' },
{ "fa-cloud-download",  L'\uf0ed' },
{ "fa-cloud-upload",  L'\uf0ee' },
{ "fa-user-md",  L'\uf0f0' },
{ "fa-stethoscope",  L'\uf0f1' },
{ "fa-suitcase",  L'\uf0f2' },
{ "fa-bell-o",  L'\uf0a2' },
{ "fa-coffee",  L'\uf0f4' },
{ "fa-cutlery",  L'\uf0f5' },
{ "fa-file-text-o",  L'\uf0f6' },
{ "fa-building-o",  L'\uf0f7' },
{ "fa-hospital-o",  L'\uf0f8' },
{ "fa-ambulance",  L'\uf0f9' },
{ "fa-medkit",  L'\uf0fa' },
{ "fa-fighter-jet",  L'\uf0fb' },
{ "fa-beer",  L'\uf0fc' },
{ "fa-h-square",  L'\uf0fd' },
{ "fa-plus-square",  L'\uf0fe' },
{ "fa-angle-double-left",  L'\uf100' },
{ "fa-angle-double-right",  L'\uf101' },
{ "fa-angle-double-up",  L'\uf102' },
{ "fa-angle-double-down",  L'\uf103' },
{ "fa-angle-left",  L'\uf104' },
{ "fa-angle-right",  L'\uf105' },
{ "fa-angle-up",  L'\uf106' },
{ "fa-angle-down",  L'\uf107' },
{ "fa-desktop",  L'\uf108' },
{ "fa-laptop",  L'\uf109' },
{ "fa-tablet",  L'\uf10a' },
{ "fa-mobile-phone",  L'\uf10b' },
{ "fa-mobile",  L'\uf10b' },
{ "fa-circle-o",  L'\uf10c' },
{ "fa-quote-left",  L'\uf10d' },
{ "fa-quote-right",  L'\uf10e' },
{ "fa-spinner",  L'\uf110' },
{ "fa-circle",  L'\uf111' },
{ "fa-mail-reply",  L'\uf112' },
{ "fa-reply",  L'\uf112' },
{ "fa-github-alt",  L'\uf113' },
{ "fa-folder-o",  L'\uf114' },
{ "fa-folder-open-o",  L'\uf115' },
{ "fa-smile-o",  L'\uf118' },
{ "fa-frown-o",  L'\uf119' },
{ "fa-meh-o",  L'\uf11a' },
{ "fa-gamepad",  L'\uf11b' },
{ "fa-keyboard-o",  L'\uf11c' },
{ "fa-flag-o",  L'\uf11d' },
{ "fa-flag-checkered",  L'\uf11e' },
{ "fa-terminal",  L'\uf120' },
{ "fa-code",  L'\uf121' },
{ "fa-mail-reply-all",  L'\uf122' },
{ "fa-reply-all",  L'\uf122' },
{ "fa-star-half-empty",  L'\uf123' },
{ "fa-star-half-full",  L'\uf123' },
{ "fa-star-half-o",  L'\uf123' },
{ "fa-location-arrow",  L'\uf124' },
{ "fa-crop",  L'\uf125' },
{ "fa-code-fork",  L'\uf126' },
{ "fa-unlink",  L'\uf127' },
{ "fa-chain-broken",  L'\uf127' },
{ "fa-question",  L'\uf128' },
{ "fa-info",  L'\uf129' },
{ "fa-exclamation",  L'\uf12a' },
{ "fa-superscript",  L'\uf12b' },
{ "fa-subscript",  L'\uf12c' },
{ "fa-eraser",  L'\uf12d' },
{ "fa-puzzle-piece",  L'\uf12e' },
{ "fa-microphone",  L'\uf130' },
{ "fa-microphone-slash",  L'\uf131' },
{ "fa-shield",  L'\uf132' },
{ "fa-calendar-o",  L'\uf133' },
{ "fa-fire-extinguisher",  L'\uf134' },
{ "fa-rocket",  L'\uf135' },
{ "fa-maxcdn",  L'\uf136' },
{ "fa-chevron-circle-left",  L'\uf137' },
{ "fa-chevron-circle-right",  L'\uf138' },
{ "fa-chevron-circle-up",  L'\uf139' },
{ "fa-chevron-circle-down",  L'\uf13a' },
{ "fa-htmlfive",  L'\uf13b' },
{ "fa-cssthree",  L'\uf13c' },
{ "fa-anchor",  L'\uf13d' },
{ "fa-unlock-alt",  L'\uf13e' },
{ "fa-bullseye",  L'\uf140' },
{ "fa-ellipsis-h",  L'\uf141' },
{ "fa-ellipsis-v",  L'\uf142' },
{ "fa-rss-square",  L'\uf143' },
{ "fa-play-circle",  L'\uf144' },
{ "fa-ticket",  L'\uf145' },
{ "fa-minus-square",  L'\uf146' },
{ "fa-minus-square-o",  L'\uf147' },
{ "fa-level-up",  L'\uf148' },
{ "fa-level-down",  L'\uf149' },
{ "fa-check-square",  L'\uf14a' },
{ "fa-pencil-square",  L'\uf14b' },
{ "fa-external-link-square",  L'\uf14c' },
{ "fa-share-square",  L'\uf14d' },
{ "fa-compass",  L'\uf14e' },
{ "fa-toggle-down",  L'\uf150' },
{ "fa-caret-square-o-down",  L'\uf150' },
{ "fa-toggle-up",  L'\uf151' },
{ "fa-caret-square-o-up",  L'\uf151' },
{ "fa-toggle-right",  L'\uf152' },
{ "fa-caret-square-o-right",  L'\uf152' },
{ "fa-euro",  L'\uf153' },
{ "fa-eur",  L'\uf153' },
{ "fa-gbp",  L'\uf154' },
{ "fa-dollar",  L'\uf155' },
{ "fa-usd",  L'\uf155' },
{ "fa-rupee",  L'\uf156' },
{ "fa-inr",  L'\uf156' },
{ "fa-cny",  L'\uf157' },
{ "fa-rmb",  L'\uf157' },
{ "fa-yen",  L'\uf157' },
{ "fa-jpy",  L'\uf157' },
{ "fa-ruble",  L'\uf158' },
{ "fa-rouble",  L'\uf158' },
{ "fa-rub",  L'\uf158' },
{ "fa-won",  L'\uf159' },
{ "fa-krw",  L'\uf159' },
{ "fa-bitcoin",  L'\uf15a' },
{ "fa-btc",  L'\uf15a' },
{ "fa-file",  L'\uf15b', 1 },
{ "fa-file-text",  L'\uf15c' },
{ "fa-sort-alpha-asc",  L'\uf15d' },
{ "fa-sort-alpha-desc",  L'\uf15e' },
{ "fa-sort-amount-asc",  L'\uf160' },
{ "fa-sort-amount-desc",  L'\uf161' },
{ "fa-sort-numeric-asc",  L'\uf162' },
{ "fa-sort-numeric-desc",  L'\uf163' },
{ "fa-thumbs-up",  L'\uf164' },
{ "fa-thumbs-down",  L'\uf165' },
{ "fa-youtube-square",  L'\uf166' },
{ "fa-youtube",  L'\uf167' },
{ "fa-xing",  L'\uf168' },
{ "fa-xing-square",  L'\uf169' },
{ "fa-youtube-play",  L'\uf16a' },
{ "fa-dropbox",  L'\uf16b' },
{ "fa-stack-overflow",  L'\uf16c' },
{ "fa-instagram",  L'\uf16d' },
{ "fa-flickr",  L'\uf16e' },
{ "fa-adn",  L'\uf170' },
{ "fa-bitbucket",  L'\uf171' },
{ "fa-bitbucket-square",  L'\uf172' },
{ "fa-tumblr",  L'\uf173' },
{ "fa-tumblr-square",  L'\uf174' },
{ "fa-long-arrow-down",  L'\uf175' },
{ "fa-long-arrow-up",  L'\uf176' },
{ "fa-long-arrow-left",  L'\uf177' },
{ "fa-long-arrow-right",  L'\uf178' },
{ "fa-apple",  L'\uf179' },
{ "fa-windows",  L'\uf17a' },
{ "fa-android",  L'\uf17b' },
{ "fa-linux",  L'\uf17c' },
{ "fa-dribbble",  L'\uf17d' },
{ "fa-skype",  L'\uf17e' },
{ "fa-foursquare",  L'\uf180' },
{ "fa-trello",  L'\uf181' },
{ "fa-female",  L'\uf182' },
{ "fa-male",  L'\uf183' },
{ "fa-gittip",  L'\uf184' },
{ "fa-gratipay",  L'\uf184' },
{ "fa-sun-o",  L'\uf185' },
{ "fa-moon-o",  L'\uf186' },
{ "fa-archive",  L'\uf187' },
{ "fa-bug",  L'\uf188' },
{ "fa-vk",  L'\uf189' },
{ "fa-weibo",  L'\uf18a' },
{ "fa-renren",  L'\uf18b' },
{ "fa-pagelines",  L'\uf18c' },
{ "fa-stack-exchange",  L'\uf18d' },
{ "fa-arrow-circle-o-right",  L'\uf18e' },
{ "fa-arrow-circle-o-left",  L'\uf190' },
{ "fa-toggle-left",  L'\uf191' },
{ "fa-caret-square-o-left",  L'\uf191' },
{ "fa-dot-circle-o",  L'\uf192' },
{ "fa-wheelchair",  L'\uf193' },
{ "fa-vimeo-square",  L'\uf194' },
{ "fa-turkish-lira",  L'\uf195' },
{ "fa-try",  L'\uf195' },
{ "fa-plus-square-o",  L'\uf196' },
{ "fa-space-shuttle",  L'\uf197' },
{ "fa-slack",  L'\uf198' },
{ "fa-envelope-square",  L'\uf199' },
{ "fa-wordpress",  L'\uf19a' },
{ "fa-openid",  L'\uf19b' },
{ "fa-institution",  L'\uf19c' },
{ "fa-bank",  L'\uf19c' },
{ "fa-university",  L'\uf19c' },
{ "fa-mortar-board",  L'\uf19d' },
{ "fa-graduation-cap",  L'\uf19d' },
{ "fa-yahoo",  L'\uf19e' },
{ "fa-google",  L'\uf1a0' },
{ "fa-reddit",  L'\uf1a1' },
{ "fa-reddit-square",  L'\uf1a2' },
{ "fa-stumbleupon-circle",  L'\uf1a3' },
{ "fa-stumbleupon",  L'\uf1a4' },
{ "fa-delicious",  L'\uf1a5' },
{ "fa-digg",  L'\uf1a6' },
{ "fa-pied-piper-pp",  L'\uf1a7' },
{ "fa-pied-piper-alt",  L'\uf1a8' },
{ "fa-drupal",  L'\uf1a9' },
{ "fa-joomla",  L'\uf1aa' },
{ "fa-language",  L'\uf1ab' },
{ "fa-x",  L'\uf1ac' },
{ "fa-building",  L'\uf1ad' },
{ "fa-child",  L'\uf1ae' },
{ "fa-paw",  L'\uf1b0' },
{ "fa-spoon",  L'\uf1b1' },
{ "fa-cube",  L'\uf1b2' },
{ "fa-cubes",  L'\uf1b3' },
{ "fa-behance",  L'\uf1b4' },
{ "fa-behance-square",  L'\uf1b5' },
{ "fa-steam",  L'\uf1b6' },
{ "fa-steam-square",  L'\uf1b7' },
{ "fa-recycle",  L'\uf1b8' },
{ "fa-automobile",  L'\uf1b9' },
{ "fa-car",  L'\uf1b9' },
{ "fa-cab",  L'\uf1ba' },
{ "fa-taxi",  L'\uf1ba' },
{ "fa-tree",  L'\uf1bb' },
{ "fa-spotify",  L'\uf1bc' },
{ "fa-deviantart",  L'\uf1bd' },
{ "fa-soundcloud",  L'\uf1be' },
{ "fa-database",  L'\uf1c0' },
{ "fa-file-pdf-o",  L'\uf1c1' },
{ "fa-file-word-o",  L'\uf1c2' },
{ "fa-file-excel-o",  L'\uf1c3' },
{ "fa-file-powerpoint-o",  L'\uf1c4' },
{ "fa-file-photo-o",  L'\uf1c5' },
{ "fa-file-picture-o",  L'\uf1c5' },
{ "fa-file-image-o",  L'\uf1c5' },
{ "fa-file-zip-o",  L'\uf1c6' },
{ "fa-file-archive-o",  L'\uf1c6' },
{ "fa-file-sound-o",  L'\uf1c7' },
{ "fa-file-audio-o",  L'\uf1c7' },
{ "fa-file-movie-o",  L'\uf1c8' },
{ "fa-file-video-o",  L'\uf1c8' },
{ "fa-file-code-o",  L'\uf1c9' },
{ "fa-vine",  L'\uf1ca' },
{ "fa-codepen",  L'\uf1cb' },
{ "fa-jsfiddle",  L'\uf1cc' },
{ "fa-life-bouy",  L'\uf1cd' },
{ "fa-life-buoy",  L'\uf1cd' },
{ "fa-life-saver",  L'\uf1cd' },
{ "fa-support",  L'\uf1cd' },
{ "fa-life-ring",  L'\uf1cd' },
{ "fa-circle-o-notch",  L'\uf1ce' },
{ "fa-ra",  L'\uf1d0' },
{ "fa-resistance",  L'\uf1d0' },
{ "fa-rebel",  L'\uf1d0' },
{ "fa-ge",  L'\uf1d1' },
{ "fa-empire",  L'\uf1d1' },
{ "fa-git-square",  L'\uf1d2' },
{ "fa-git",  L'\uf1d3' },
{ "fa-y-combinator-square",  L'\uf1d4' },
{ "fa-yc-square",  L'\uf1d4' },
{ "fa-hacker-news",  L'\uf1d4' },
{ "fa-tencent-weibo",  L'\uf1d5' },
{ "fa-qq",  L'\uf1d6' },
{ "fa-wechat",  L'\uf1d7' },
{ "fa-weixin",  L'\uf1d7' },
{ "fa-send",  L'\uf1d8' },
{ "fa-paper-plane",  L'\uf1d8' },
{ "fa-send-o",  L'\uf1d9' },
{ "fa-paper-plane-o",  L'\uf1d9' },
{ "fa-history",  L'\uf1da' },
{ "fa-circle-thin",  L'\uf1db' },
{ "fa-header",  L'\uf1dc' },
{ "fa-paragraph",  L'\uf1dd' },
{ "fa-sliders",  L'\uf1de' },
{ "fa-share-alt",  L'\uf1e0' },
{ "fa-share-alt-square",  L'\uf1e1' },
{ "fa-bomb",  L'\uf1e2' },
{ "fa-soccer-ball-o",  L'\uf1e3' },
{ "fa-futbol-o",  L'\uf1e3' },
{ "fa-tty",  L'\uf1e4' },
{ "fa-binoculars",  L'\uf1e5' },
{ "fa-plug",  L'\uf1e6' },
{ "fa-slideshare",  L'\uf1e7' },
{ "fa-twitch",  L'\uf1e8' },
{ "fa-yelp",  L'\uf1e9' },
{ "fa-newspaper-o",  L'\uf1ea' },
{ "fa-wifi",  L'\uf1eb' },
{ "fa-calculator",  L'\uf1ec' },
{ "fa-paypal",  L'\uf1ed' },
{ "fa-google-wallet",  L'\uf1ee' },
{ "fa-cc-visa",  L'\uf1f0' },
{ "fa-cc-mastercard",  L'\uf1f1' },
{ "fa-cc-discover",  L'\uf1f2' },
{ "fa-cc-amex",  L'\uf1f3' },
{ "fa-cc-paypal",  L'\uf1f4' },
{ "fa-cc-stripe",  L'\uf1f5' },
{ "fa-bell-slash",  L'\uf1f6' },
{ "fa-bell-slash-o",  L'\uf1f7' },
{ "fa-trash",  L'\uf1f8' },
{ "fa-copyright",  L'\uf1f9' },
{ "fa-at",  L'\uf1fa' },
{ "fa-eyedropper",  L'\uf1fb' },
{ "fa-paint-brush",  L'\uf1fc' },
{ "fa-birthday-cake",  L'\uf1fd' },
{ "fa-area-chart",  L'\uf1fe' },
{ "fa-pie-chart",  L'\uf200' },
{ "fa-line-chart",  L'\uf201' },
{ "fa-lastfm",  L'\uf202' },
{ "fa-lastfm-square",  L'\uf203' },
{ "fa-toggle-off",  L'\uf204' },
{ "fa-toggle-on",  L'\uf205' },
{ "fa-bicycle",  L'\uf206' },
{ "fa-bus",  L'\uf207' },
{ "fa-ioxhost",  L'\uf208' },
{ "fa-angellist",  L'\uf209' },
{ "fa-cc",  L'\uf20a' },
{ "fa-shekel",  L'\uf20b' },
{ "fa-sheqel",  L'\uf20b' },
{ "fa-ils",  L'\uf20b' },
{ "fa-meanpath",  L'\uf20c' },
{ "fa-buysellads",  L'\uf20d' },
{ "fa-connectdevelop",  L'\uf20e' },
{ "fa-dashcube",  L'\uf210' },
{ "fa-forumbee",  L'\uf211' },
{ "fa-leanpub",  L'\uf212' },
{ "fa-sellsy",  L'\uf213' },
{ "fa-shirtsinbulk",  L'\uf214' },
{ "fa-simplybuilt",  L'\uf215' },
{ "fa-skyatlas",  L'\uf216' },
{ "fa-cart-plus",  L'\uf217' },
{ "fa-cart-arrow-down",  L'\uf218' },
{ "fa-diamond",  L'\uf219' },
{ "fa-ship",  L'\uf21a' },
{ "fa-user-secret",  L'\uf21b' },
{ "fa-motorcycle",  L'\uf21c' },
{ "fa-street-view",  L'\uf21d' },
{ "fa-heartbeat",  L'\uf21e' },
{ "fa-venus",  L'\uf221' },
{ "fa-mars",  L'\uf222' },
{ "fa-mercury",  L'\uf223' },
{ "fa-intersex",  L'\uf224' },
{ "fa-transgender",  L'\uf224' },
{ "fa-transgender-alt",  L'\uf225' },
{ "fa-venus-double",  L'\uf226' },
{ "fa-mars-double",  L'\uf227' },
{ "fa-venus-mars",  L'\uf228' },
{ "fa-mars-stroke",  L'\uf229' },
{ "fa-mars-stroke-v",  L'\uf22a' },
{ "fa-mars-stroke-h",  L'\uf22b' },
{ "fa-neuter",  L'\uf22c' },
{ "fa-genderless",  L'\uf22d' },
{ "fa-cebook-official",  L'\uf230' },
{ "fa-pinterest-p",  L'\uf231' },
{ "fa-whatsapp",  L'\uf232' },
{ "fa-server",  L'\uf233' },
{ "fa-user-plus",  L'\uf234' },
{ "fa-user-times",  L'\uf235' },
{ "fa-hotel",  L'\uf236' },
{ "fa-bed",  L'\uf236' },
{ "fa-viacoin",  L'\uf237' },
{ "fa-train",  L'\uf238' },
{ "fa-subway",  L'\uf239' },
{ "fa-medium",  L'\uf23a' },
{ "fa-yc",  L'\uf23b' },
{ "fa-y-combinator",  L'\uf23b' },
{ "fa-optin-monster",  L'\uf23c' },
{ "fa-opencart",  L'\uf23d' },
{ "fa-expeditedssl",  L'\uf23e' },
{ "fa-battery-four",  L'\uf240' },
{ "fa-battery",  L'\uf240' },
{ "fa-battery-full",  L'\uf240' },
{ "fa-battery-three",  L'\uf241' },
{ "fa-battery-three-quarters",  L'\uf241' },
{ "fa-battery-two",  L'\uf242' },
{ "fa-battery-half",  L'\uf242' },
{ "fa-battery-one",  L'\uf243' },
{ "fa-battery-quarter",  L'\uf243' },
{ "fa-battery-zero",  L'\uf244' },
{ "fa-battery-empty",  L'\uf244' },
{ "fa-mouse-pointer",  L'\uf245' },
{ "fa-i-cursor",  L'\uf246' },
{ "fa-object-group",  L'\uf247' },
{ "fa-object-ungroup",  L'\uf248' },
{ "fa-sticky-note",  L'\uf249' },
{ "fa-sticky-note-o",  L'\uf24a' },
{ "fa-cc-jcb",  L'\uf24b' },
{ "fa-cc-diners-club",  L'\uf24c' },
{ "fa-clone",  L'\uf24d' },
{ "fa-balance-scale",  L'\uf24e' },
{ "fa-hourglass-o",  L'\uf250' },
{ "fa-hourglass-one",  L'\uf251' },
{ "fa-hourglass-start",  L'\uf251' },
{ "fa-hourglass-two",  L'\uf252' },
{ "fa-hourglass-half",  L'\uf252' },
{ "fa-hourglass-three",  L'\uf253' },
{ "fa-hourglass-end",  L'\uf253' },
{ "fa-hourglass",  L'\uf254' },
{ "fa-hand-grab-o",  L'\uf255' },
{ "fa-hand-rock-o",  L'\uf255' },
{ "fa-hand-stop-o",  L'\uf256' },
{ "fa-hand-paper-o",  L'\uf256' },
{ "fa-hand-scissors-o",  L'\uf257' },
{ "fa-hand-lizard-o",  L'\uf258' },
{ "fa-hand-spock-o",  L'\uf259' },
{ "fa-hand-pointer-o",  L'\uf25a' },
{ "fa-hand-peace-o",  L'\uf25b' },
{ "fa-trademark",  L'\uf25c' },
{ "fa-registered",  L'\uf25d' },
{ "fa-creative-commons",  L'\uf25e' },
{ "fa-gg",  L'\uf260' },
{ "fa-gg-circle",  L'\uf261' },
{ "fa-tripadvisor",  L'\uf262' },
{ "fa-odnoklassniki",  L'\uf263' },
{ "fa-odnoklassniki-square",  L'\uf264' },
{ "fa-get-pocket",  L'\uf265' },
{ "fa-wikipedia-w",  L'\uf266' },
{ "fa-sari",  L'\uf267' },
{ "fa-chrome",  L'\uf268' },
{ "fa-firefox",  L'\uf269' },
{ "fa-opera",  L'\uf26a' },
{ "fa-internet-explorer",  L'\uf26b' },
{ "fa-tv",  L'\uf26c' },
{ "fa-television",  L'\uf26c' },
{ "fa-contao",  L'\uf26d' },
{ "fa-fivezerozeropx",  L'\uf26e' },
{ "fa-amazon",  L'\uf270' },
{ "fa-calendar-plus-o",  L'\uf271' },
{ "fa-calendar-minus-o",  L'\uf272' },
{ "fa-calendar-times-o",  L'\uf273' },
{ "fa-calendar-check-o",  L'\uf274' },
{ "fa-industry",  L'\uf275' },
{ "fa-map-pin",  L'\uf276' },
{ "fa-map-signs",  L'\uf277' },
{ "fa-map-o",  L'\uf278' },
{ "fa-map",  L'\uf279' },
{ "fa-commenting",  L'\uf27a' },
{ "fa-commenting-o",  L'\uf27b' },
{ "fa-houzz",  L'\uf27c' },
{ "fa-vimeo",  L'\uf27d' },
{ "fa-black-tie",  L'\uf27e' },
{ "fa-fonticons",  L'\uf280' },
{ "fa-reddit-alien",  L'\uf281' },
{ "fa-edge",  L'\uf282' },
{ "fa-credit-card-alt",  L'\uf283' },
{ "fa-codiepie",  L'\uf284' },
{ "fa-modx",  L'\uf285' },
{ "fa-fort-awesome",  L'\uf286' },
{ "fa-usb",  L'\uf287' },
{ "fa-product-hunt",  L'\uf288' },
{ "fa-mixcloud",  L'\uf289' },
{ "fa-scribd",  L'\uf28a' },
{ "fa-pause-circle",  L'\uf28b' },
{ "fa-pause-circle-o",  L'\uf28c' },
{ "fa-stop-circle",  L'\uf28d', 1 },
{ "fa-stop-circle-o",  L'\uf28e', 1 },
{ "fa-shopping-bag",  L'\uf290' },
{ "fa-shopping-basket",  L'\uf291' },
{ "fa-hashtag",  L'\uf292' },
{ "fa-bluetooth",  L'\uf293' },
{ "fa-bluetooth-b",  L'\uf294' },
{ "fa-percent",  L'\uf295' },
{ "fa-gitlab",  L'\uf296' },
{ "fa-wpbeginner",  L'\uf297' },
{ "fa-wpforms",  L'\uf298' },
{ "fa-envira",  L'\uf299' },
{ "fa-universal-access",  L'\uf29a' },
{ "fa-wheelchair-alt",  L'\uf29b' },
{ "fa-circle-question",  L'\uf059', 1 },
{ "fa-question-circle-o",  L'\uf29c' },
{ "fa-blind",  L'\uf29d' },
{ "fa-audio-description",  L'\uf29e' },
{ "fa-volume-control-phone",  L'\uf2a0' },
{ "fa-braille",  L'\uf2a1' },
{ "fa-assistive-listening-systems",  L'\uf2a2' },
{ "fa-asl-interpreting",  L'\uf2a3' },
{ "fa-american-sign-language-interpreting",  L'\uf2a3' },
{ "fa-deafness",  L'\uf2a4' },
{ "fa-hard-of-hearing",  L'\uf2a4' },
{ "fa-deaf",  L'\uf2a4' },
{ "fa-glide",  L'\uf2a5' },
{ "fa-glide-g",  L'\uf2a6' },
{ "fa-signing",  L'\uf2a7' },
{ "fa-sign-language",  L'\uf2a7' },
{ "fa-low-vision",  L'\uf2a8' },
{ "fa-viadeo",  L'\uf2a9' },
{ "fa-viadeo-square",  L'\uf2aa' },
{ "fa-snapchat",  L'\uf2ab' },
{ "fa-snapchat-ghost",  L'\uf2ac' },
{ "fa-snapchat-square",  L'\uf2ad' },
{ "fa-pied-piper",  L'\uf2ae' },
{ "fa-first-order",  L'\uf2b0' },
{ "fa-yoast",  L'\uf2b1' },
{ "fa-themeisle",  L'\uf2b2' },
{ "fa-google-plus-circle",  L'\uf2b3' },
{ "fa-google-plus-official",  L'\uf2b3' },
{ "fa-f-a",  L'\uf2b4' },
{ "fa-font-awesome",  L'\uf2b4' },
{ "fa-handshake-o",  L'\uf2b5' },
{ "fa-envelope-open",  L'\uf2b6' },
{ "fa-envelope-open-o",  L'\uf2b7' },
{ "fa-linode",  L'\uf2b8' },
{ "fa-address-book",  L'\uf2b9' },
{ "fa-address-book-o",  L'\uf2ba' },
{ "fa-vcard",  L'\uf2bb' },
{ "fa-address-card",  L'\uf2bb' },
{ "fa-vcard-o",  L'\uf2bc' },
{ "fa-address-card-o",  L'\uf2bc' },
{ "fa-user-circle",  L'\uf2bd' },
{ "fa-user-circle-o",  L'\uf2be' },
{ "fa-user-o",  L'\uf2c0' },
{ "fa-id-badge",  L'\uf2c1' },
{ "fa-drivers-license",  L'\uf2c2' },
{ "fa-id-card",  L'\uf2c2' },
{ "fa-drivers-license-o",  L'\uf2c3' },
{ "fa-id-card-o",  L'\uf2c3' },
{ "fa-quora",  L'\uf2c4' },
{ "fa-free-code-camp",  L'\uf2c5' },
{ "fa-telegram",  L'\uf2c6' },
{ "fa-thermometer-four",  L'\uf2c7' },
{ "fa-thermometer",  L'\uf2c7' },
{ "fa-thermometer-full",  L'\uf2c7' },
{ "fa-thermometer-three",  L'\uf2c8' },
{ "fa-thermometer-three-quarters",  L'\uf2c8' },
{ "fa-thermometer-two",  L'\uf2c9' },
{ "fa-thermometer-half",  L'\uf2c9' },
{ "fa-thermometer-one",  L'\uf2ca' },
{ "fa-thermometer-quarter",  L'\uf2ca' },
{ "fa-thermometer-zero",  L'\uf2cb' },
{ "fa-thermometer-empty",  L'\uf2cb' },
{ "fa-shower",  L'\uf2cc' },
{ "fa-bathtub",  L'\uf2cd' },
{ "fa-sonefive",  L'\uf2cd' },
{ "fa-bath",  L'\uf2cd' },
{ "fa-podcast",  L'\uf2ce' },
{ "fa-window-maximize",  L'\uf2d0' },
{ "fa-window-minimize",  L'\uf2d1' },
{ "fa-window-restore",  L'\uf2d2' },
{ "fa-rectangle-xmark",  L'\uf410', 1 },
{ "fa-times-rectangle",  L'\uf2d3' },
{ "fa-window-close",  L'\uf2d3' },
{ "fa-times-rectangle-o",  L'\uf2d4' },
{ "fa-window-close-o",  L'\uf2d4' },
{ "fa-bandcamp",  L'\uf2d5' },
{ "fa-grav",  L'\uf2d6' },
{ "fa-etsy",  L'\uf2d7' },
{ "fa-imdb",  L'\uf2d8' },
{ "fa-ravelry",  L'\uf2d9' },
{ "fa-eercast",  L'\uf2da' },
{ "fa-snowflake-o",  L'\uf2dc' },
{ "fa-superpowers",  L'\uf2dd' },
{ "fa-wpexplorer",  L'\uf2de' },
{ "fa-meetup",  L'\uf2e0' },
{ "fa-message", L'\uf27a' },
{ "fa-comment-slash", L'\uf4b3' },
{ "fa-laptop-code", L'\uf5fc' },
{ "fa-hashtag", L'\u0023' },
{ "fa-list-check", L'\uf0ae' },
{ "fa-folder-tree", L'\uf802' },
{ "fa-searchengin", L'\uf3eb' },
{ "fa-magnifying-glass-arrow-right", L'\ue521' },
{ "fa-microchip", L'\uf2db' },
{ "fa-delete-left", L'\uf55a' }
};

static HASHMAP* _faIconNameMap;

/*
 * Returns the unicode equivalent of a font-awesome icon given its name as e.g. "fa-meetup".
 */
CHAR_WITH_STYLE faicon_codeForName(const char* pszIconName) {
	if (!_faIconNameMap) {
		_faIconNameMap = hashmap_create(512, 0, 0);
		for (int i = 0; i < sizeof(_faIcons) / sizeof(_faIcons[0]); i++) {
			hashmap_put(_faIconNameMap, _faIcons[i].fa_name, (intptr_t)_faIcons[i].fa_code);
		}
	}
	char* pszStyle = strchr(pszIconName, ' ');
	int regular = 0;
	char name[128];
	if (pszStyle && strcmp(pszStyle + 1, "regular") == 0) {
		int len = (int)(pszStyle - pszIconName);
		if (len > 127) {
			len = 127;
		}
		strncpy(name, pszIconName, len);
		name[len] = 0;
		regular = 1;
		pszIconName = name;
	}
	return (CHAR_WITH_STYLE) {
		.regular = regular,
		.symbol = (wchar_t)hashmap_get(_faIconNameMap, pszIconName)
	};
}

/*
 * Cleanup the font awesome icon component.
 */
void faicon_destroy() {
	hashmap_destroy(_faIconNameMap, 0);
}

/*
 * Can be used to iterate all icon names. If the icon with the givem index does not exist, NULL is returned.
 */
const char* faicon_nameForIndex(int nIndex) {
	if (nIndex < 0 || nIndex >= sizeof(_faIcons) / sizeof(_faIcons[0])) {
		return NULL;
	}
	return _faIcons[nIndex].fa_name;
}

