/*
 * FunctionTable.c
 *
 * PROJEKT: PKS-EDIT for ATARI / MS Windows
 *
 * purpose:
 * definition of all functions and commands callable in PKS Edit,
 * which can be used either in macros or bound to menus / keyboard etc...
 *
 * 										created: 20.02.87
 * 										last modified:
 *										author: Tom
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

#include <windows.h>
#include "edfuncs.h"
#include "funcdef.h"
#include "pksedit.h"
#include "edierror.h"
#include "publicapi.h"
#include "findandreplace.h"
#include "iccall.h"
#include "winfo.h"
#include "pksrc.h"
#include "menu.h"
#include "markpositions.h"
#include "windowselector.h"
#include "edierror.h"
#include "editoperations.h"
#include "mainframe.h"
#include "comparefiles.h"
#include "evaluator.h"

extern int
EdFileAbandon(), EdAbout(long ), EdBlockCopy(long ), EdBlockDelete(),
EdBlockFindEnd(long ), EdBlockFindStart(long ), EdBlockMove(long ), EdBlockRead(long ),
EdBlockWrite(long ), bl_cutOrCopy(long ), EdBlockPaste(long ), bl_hideSelectionInCurrentWindow(),
EdSyncSelectionWithCaret(long ), bl_cutLines(long ), EdLineDelete(long ), bl_destroyAll(long ),
EdKeycodeInsert(long ), EdCharInsert(long ), EdFormatText(long ), edit_insertLine(long ),
EdSearchListRead(long ), EdErrorListRead(long ), 
EdMacrosEdit(long ), EdDocMacrosEdit(long ), EdDocMacrosAdd(long ), macro_readWriteWithFileSelection(long ),
EdTagfileRead(long ), EdSetup(long ), EdSetMultiplier(long ), EdReplaceTabs(long ),
EdLineSplit(int), EdParaGotoBegin(long ), edit_shiftSelection(int aDirection),
EdParaGotoEnd(long ), EdCharDelete(long ), fkey_keyModifierStateChanged(long ), codecomplete_showSuggestionWindow(long ),
macro_executeMacroByIndex(long ), EdMacroRecord(long ), EdFindInFileList(long ), EdFind(long ),
EdReplace(long ), EdFindAgain(long ), EdReplaceAgain(long ), EdCharControlInsert(long ),
EdGotoLine(long ), EdMarkSet(long ), EdMarkGoto(long ),
EdLinesJoin(long ), EdEditFile(long, char* filename), EdOptionSet(long ),
EdPrint(long ), EdExitAndSave(long ), EdExit(long ), EdCloseAll(),
EdSaveFile(int ), EdSelectWindow(int), EdCommandExecute(long ), EdExecute(long ),
EdShiftBetweenBrackets(long ), EdSort(long ), EdLinesShift(long ), EdInfoFiles(long ),
EdShowMatch(long ), dlg_configureEditorModes(long ),
EdOptionToggle(long ), EdPasteString(long ),
EdFindTag(long ), EdFindFileCursor(long ), xref_navigateSearchErrorList(long ), EdFindTagCursor(long ),
EdFindWordCursor(long ), EdRangeShift(long ),
EdUndo(long ), EdRedo(long), EdFilesCompare(long ), EdScrollScreen(long ), EdScrollCursor(long ),
EdAlignText(long ), EdBlockMouseMark(long ),
EdMouseMarkParts(long ), EdMouseMoveText(long ), EdMouseSelectLines(long ), EdMousePositionUngrabbed(long ),
EdAlert(long ), error_displayAlertBoxWithOptions(long ), EdPromptAssign(long ), EdFormatPrint(long ),
macro_getSelectedText(long ), EdHideLines(long ), EdUnHideLine(long ), EdStringSubstitute(long ),
EdExpandAbbreviation(long ), EdConfigureIcons(long ), EdHelpContext(long ), EdListBindings(long ),
EdCompileMacros(long ), EdDocTypes(long ), EdIsDefined(long ), ft_cloneWindow(), ww_zoomWindow(int anIncreaseFactor),
bl_moveSelectionUpDown(long),
EdShowClipboard(long ), EdSaveAllFiles(), EdBlockXtndMode(long ), edit_toggleComment(),EdFindOnInternet();

static int function_unused() {
    // NOT USED ANY MORE
    return 0;
}

EDFUNC _edfunctab[] = {
{/*0*/   EdFileAbandon , '!',EW_NEEDSCURRF | 0,                                                  "AbandonFile",     NULL },
{/*1*/   EdAbout       , '!',0,                                                                  "About",           NULL },
{/*2*/   EdBlockCopy   , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,          "CopyBlock",       NULL },
{/*3*/   EdBlockDelete , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,          "DeleteBlock",     NULL },
{/*4*/   EdBlockFindEnd, '!',EW_NEEDSCURRF | EW_NEEDSBLK | 0,                                   "FindBlockEnd",NULL },
{/*5*/   EdBlockFindStart, '!',  EW_NEEDSCURRF | EW_NEEDSBLK | 0,                               "FindBlockStart",NULL },
{/*6*/   EdBlockMove   , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,         		"MoveBlock",NULL },
{/*7*/   EdBlockRead   , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                       		"ReadBlock",NULL },
{/*8*/   EdBlockWrite  , '!',EW_NEEDSCURRF | EW_NEEDSBLK | 0,                                        	"WriteBlock",NULL },
{/*9*/   bl_cutOrCopy    , '!',EW_UNDOFLSH|EW_NEEDSCURRF | EW_NEEDSBLK | 0,                          	"CutBlock",NULL },
{/*10*/  EdBlockPaste  , '!',EW_MODIFY | EW_FINDCURS | EW_NEEDSCURRF | EW_UNDOFLSH | 0,             	"PasteBlock",NULL },
{/*11*/  bl_hideSelectionInCurrentWindow   , '!',EW_NEEDSCURRF | 0,                                  	"HideBlock",NULL },
{/*12*/  EdSyncSelectionWithCaret   , '!',   EW_NEEDSCURRF | 0,                                      	"SetBlockMark",NULL },
{/*13*/  bl_cutLines   , '!',EW_NEEDSCURRF | EW_MULTI | 0,                                           	"CutLines",NULL },
{/*14*/  EdLineDelete  , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                            	"DeleteLines",NULL },
{/*15*/  bl_destroyAll  , '!',0,                                                                      	"FreeBuffer",NULL },
{/*16*/  EdKeycodeInsert, '!',   EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                        	"InsertKeycode",NULL },
{/*17*/  EdCharInsert  , '!',EW_MODIFY | EW_NEEDSCURRF | EW_CCASH | 0,                               	"InsertChar",NULL },
{/*18*/	 EdFormatText  , '!',EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_CUSTOM_ENABLEMENT,            "FormatText",ft_supportsFormatting },
{/*19*/	 edit_insertLine  , '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                        	"InsertLine",NULL },
{/*20*/	 edit_performLineFlagOperation, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                "MarkLineOp",NULL },
{/*21*/	 EdSearchListRead, '!', EW_HASFORM | 0,                                                          "ReadSearchList",NULL },
{/*22*/	 EdErrorListRead, '!', 0,                                                                        "ReadErrorList",NULL },
{/*23*/	 ww_zoomWindow, '!', EW_NEEDSCURRF | 0,                                                          "RwModus",NULL },
{/*24*/	 EdMacrosEdit, '!', EW_MULTI | 0,                                                                "EditMacros",NULL },
{/*25*/	 EdDocMacrosEdit, '!', 0,                                                                        "EditDocMacros", NULL },
{/*26*/	 EdDocMacrosAdd, '!', EW_HASFORM | 0,                                                            "MergeDocMacrosWith",NULL },
{/*27*/	 macro_readWriteWithFileSelection, '!', EW_HASFORM | 0,                                          "RwMacros",NULL },
{/*28*/	 EdTagfileRead, '!', EW_HASFORM | 0,                                                             "ReadTagfile",NULL },
{/*29*/	 EdSetup, '!', 0,                                                                                "RwSetup",NULL },
{/*30*/	 EdSetMultiplier, '!', 0,                                                                        "SetMultiplier",NULL },
{/*31*/	 EdReplaceTabs, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                "ReplaceTabs",NULL },
{/*32*/	 EdLineSplit, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                  "SplitLine",NULL },
{/*33*/	 EdChapterGotoBegin, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                          "GotoChapterStart",NULL },
{/*34*/	 EdChapterGotoEnd, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                            "GotoChapterEnd",NULL },
{/*35*/	 EdParaGotoBegin, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                             "GotoPgrphStart",NULL },
{/*36*/	 EdParaGotoEnd, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                               "GotoPgrphEnd",NULL },
{/*37*/	 EdCursorRight, '!', EW_NEEDSCURRF | 0,                                                          "CursorRight",NULL },
{/*38*/	 EdCursorLeft, '!', EW_NEEDSCURRF | 0,                                                           "CursorLeft",NULL },
{/*39*/	 EdCursorUp, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                                  "CursorUp",NULL },
{/*40*/	 EdCursorDown, '!', EW_NEEDSCURRF | EW_MULTI | 0,                                                "CursorDown",NULL },
{/*41*/	 EdCharDelete, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                 "Delete",NULL },
{/*42*/	 fkey_keyModifierStateChanged, '!', 0,                                                           "SwitchFkeys",NULL },
{/*43*/	 codecomplete_showSuggestionWindow, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_HASFORM ,  "CodeCompleteSuggest",NULL },
{/*44*/	 macro_executeMacroByIndex, '!', EW_NOCASH | EW_CCASH | 0,                                       "PlayMacro",NULL },
{/*45*/	 EdMacroRecord, '!', EW_NOCASH | 0,                                                              "RecordMacro",NULL },
{/*46*/	 EdFindInFileList, '!', EW_HASFORM | 0,                                                          "FindInFileList",NULL },
{/*47*/	 EdFind, '!', EW_NEEDSCURRF | EW_HASFORM | 0,                                                    "Find",NULL },
{/*48*/	 EdReplace, '!', EW_MODIFY | EW_NEEDSCURRF | EW_HASFORM | 0,                                     "Replace",NULL },
{/*49*/	 EdFindAgain, '!', EW_NEEDSCURRF | 0,                                                            "FindAgain",NULL },
{/*50*/	 EdReplaceAgain, '!', EW_MODIFY | EW_NEEDSCURRF | 0,                                             "ReplaceAgain",NULL },
{/*51*/	 EdCharControlInsert, '!', EW_MODIFY | EW_NEEDSCURRF | EW_HASFORM | EW_CCASH | 0,                "InsertControl",NULL },
{/*52*/	 fm_gotoNextPosition, '!', EW_CUSTOM_ENABLEMENT,                                 "GotoLastpos", fm_canGotoNext},
{/*53*/	 EdGotoLine, '!', EW_NEEDSCURRF | 0,                                                             "GotoLine",NULL },
{/*54*/	 EdMarkSet, '!', EW_NEEDSCURRF | EW_HASFORM | 0,                                                 "SetMark",NULL },
{/*55*/	 EdMarkGoto, '!', EW_NEEDSCURRF | EW_HASFORM | 0,                                                "GotoMark",NULL },
{/*56*/	 menu_openContextMenu, '!', 0,                                                                   "OpenContextMenu",NULL },
{/*57*/	 EdLinesJoin, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                  "JoinLines",NULL },
{/*58*/	 EdEditFile, '!', EW_HASFORM | 0,                                                                "EditFile",NULL },
{/*59*/	 EdOptionSet, '!', EW_HASFORM | 0,                                                               "SetOptions",NULL },
{/*60*/	 EdPrint, '!', 0,                                                                                "Print",NULL },
{/*62*/	 EdExitAndSave, '!', 0,                                                                          "ExitEdit",NULL },
{/*62*/	 EdExit, '!', 0,                                                                                 "QuitEdit",NULL },
{/*63*/	 EdCloseAll, '!', 0,                                                                             "CloseAllWindows",NULL },
{/*64*/	 EdSaveFile, '!', EW_NEEDSCURRF | 0,                                                             "SaveFile",NULL },
{/*65*/	 EdSelectWindow, '!', 0,                                                                         "SelectWindow",NULL },
{/*66*/	 EdCommandExecute, '!', EW_HASFORM | 0,                                                          "ExecuteCommand",NULL },
{/*67*/	 EdExecute, '!', EW_HASFORM | 0,                                                                 "Exec",NULL },
{/*68*/	 EdShiftBetweenBrackets, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                       "ShiftBetweenBrackets",NULL },
{/*69*/	 EdSort, '!', EW_MODIFY | EW_NEEDSCURRF | 0,                                                     "Sort",NULL },
{/*70*/	 EdLinesShift, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_MULTI | 0,                      "ShiftLines",NULL },
{/*71*/	 EdInfoFiles, '!', 0,                                                                            "ShowInfo",NULL },
{/*72*/	 EdShowMatch, '!', EW_NEEDSCURRF | 0,                                                            "CheckBrackets",NULL },
{/*73*/	 edit_convertCharacterCase, '!', EW_MODIFY | EW_FINDCURS | EW_NEEDSCURRF | EW_UNDOFLSH | 0,      "UpToLow",NULL },
{/*74*/	 evaluator_evaluateCurrentSelection, '!', EW_NEEDSCURRF | EW_FINDCURS | 0,                       "EvaluateSelection",NULL },
{/*75*/	 dlg_configureEditorModes, '!', EW_NEEDSCURRF | 0,												"SetDispMode",NULL },
{/*76*/	 mainframe_toggleFullScreen, '!', 0,															"ToggleFullScreen",NULL },
{/*77*/	 EdFindOnInternet, '!', EW_NEEDSCURRF | EW_FINDCURS | 0,                               			"FindOnInternet",NULL },
{/*78*/	 EdOptionToggle, '!', EW_NEEDSCURRF | 0,                                               			"ToggleTextMode",NULL },
{/*79*/	 EdPasteString, '!', EW_NEEDSCURRF | EW_FINDCURS | 0,                                  			"PasteString",NULL },
{/*80*/	 EdFindTag, '!', EW_HASFORM | 0,                                                       "FindTag",NULL },
{/*81*/	 EdFindFileCursor, '!', EW_NEEDSCURRF | 0,                                             "CursorFindFile",NULL },
{/*82*/	 xref_navigateSearchErrorList, '!', 0,                                                 "FindError",NULL },
{/*83*/	 EdFindTagCursor, '!', EW_NEEDSCURRF | EW_FINDCURS| 0,                                 "CursorFindTag",NULL },
{/*84*/	 EdFindWordCursor, '!', EW_NEEDSCURRF | EW_FINDCURS | 0,                                         "CursorFindWord",             NULL },
{mainframe_manageDocks, '!', 0,                                                                  "ManageDocks",NULL },
{xref_navigateSearchErrorList, '!', EW_NEEDSCURRF | EW_FINDCURS,                                 "FindErrorMouseClick",NULL },
{EdRangeShift, '!', EW_MODIFY | EW_NEEDSCURRF | EW_FINDCURS | EW_UNDOFLSH | 0,                                 "ShiftText",NULL },
{EdUndo, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDO_AVAILABLE,                                     "Undo",                       NULL },
{EdFilesCompare, '!', EW_NEEDSCURRF | 0,                                                         "CompareWindows",             NULL },
{EdScrollScreen, '!', EW_NEEDSCURRF | 0,                                                         "ScrollScreen",               NULL },
{EdScrollCursor, '!', EW_NEEDSCURRF | 0,                                                         "ScrollCursor",               NULL },
{fm_gotoLastPosition, '!', EW_CUSTOM_ENABLEMENT,                                                 "GotoLastPosition",  fm_canGotoLast},
{EdAlignText, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                  "AlignText",                  NULL },
{error_setShowMessages, '!', 0,                                                                  "ShowMessages",               NULL },
{EdBlockMouseMark, '!', EW_NEEDSCURRF | 0,                                                       "MouseMarkBlock",             NULL },
{EdMouseMarkParts, '!', EW_NEEDSCURRF | 0,                                                       "MouseMarkParts",             NULL },
{EdMouseMoveText, '!', EW_NEEDSCURRF | 0,                                                        "MouseMoveText",              NULL },
{EdMouseSelectLines, '!', EW_NEEDSCURRF | EW_FINDCURS | 0,                                       "MouseSelectLines",           NULL },
{EdMousePositionUngrabbed, '!', EW_NEEDSCURRF | 0,                                               "MousePosition",              NULL },
{EdAlert, '!', 0,                                                                                "Alert",                      NULL },
{error_displayAlertBoxWithOptions, '!', 0,                                                       "MessageBox",                 NULL },
{EdPromptAssign, '!', 0,                                                                         "PromptAssign",               NULL },
{EdFormatPrint, '!', 0,                                                                          "FormatPrint",                NULL },
{macro_getSelectedText, '!', 0,                                                                      "GetSelected",                NULL },
{EdHideLines, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                  "HideLines",                  NULL },
{EdUnHideLine, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,                                 "UnHideLine",                 NULL },
{EdStringSubstitute, '!', 0,                                                                     "ReplaceInString",            NULL },
{EdExpandAbbreviation, '!', 0,                                                                   "ExpandAbbreviation",         NULL },
{function_unused, '!', 0,                                                                       "ConfigureIcons",             NULL },
{EdHelpContext, '!', 0,                                                                          "ShowHelp",        NULL },
{EdListBindings, '!', 0,                                                                         "ListBindings",               NULL },
{EdCompileMacros, '!', EW_NEEDSCURRF | 0,                                                        "CompileMacros",              NULL },
{EdDocTypes, '!', 0,                                                                             "DefineDocTypes",             NULL },
{find_initiateIncrementalSearch, '!', EW_NEEDSCURRF,                                             "SetPrinterLayout",           NULL },
{EdIsDefined, '!', 0,                                                                            "QueryStatus",                NULL },
{function_unused, '!', 0,                                                                         "unused",                NULL },
{EdShowClipboard, '!', 0,                                                                        "ShowClipboard",              NULL },
{function_unused, '!', EW_NEEDSCURRF | 0,                                                       "unused",                 NULL },
{EdBlockXtndMode, '!', EW_NEEDSCURRF | 0,                                                        "SetBlockExtensionMode",      NULL },
{EdRedo, '!', EW_MODIFY | EW_NEEDSCURRF | EW_REDO_AVAILABLE,                                     "Redo", NULL },
{EdSaveAllFiles, '!', EW_NEEDSCURRF | 0,                                                         "SaveAll",NULL },
{/*122*/ft_cloneWindow, '!', EW_NEEDSCURRF,                                                      "CloneWindow",NULL },
{/*123*/edit_shiftSelection, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH,                       "ShiftSelection",NULL },
{/*124*/edit_toggleComment, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH,                        "ToggleComment",NULL },
{/*125*/windowselector_showWindowList,'!',0,                                                     "ShowWindowSelector",NULL },
{/*126*/compare_navigate,'!', EW_NEEDSCURRF| EW_COMPARISON_MODE,                                 "CompareNavigate",NULL },
{/*127*/compare_clear, '!', EW_NEEDSCURRF | EW_COMPARISON_MODE,                                  "CompareClear",NULL },
{/*128*/bl_moveSelectionUpDown, '!', EW_NEEDSCURRF | EW_UNDOFLSH,                                "MoveSelection", NULL }
};

int _nfuncs = sizeof(_edfunctab)/sizeof(_edfunctab[0]);
COMMAND _cmdseqtab[] = {
0, C_1FUNC, 58 /* EdEditFile */, 0 , "open-file", 
1, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN, "open-new-file", 
2, C_1FUNC, 58 /* EdEditFile */, OPEN_DIRGIVEN, "open-file-dir-given", 
3, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_LINEAL, "open-special",
4, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_HISTORY|0x0000, "open-history",
5, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_HISTORY|0x1000, "open-history1",
6, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_HISTORY|0x2000, "open-history2",
7, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_HISTORY|0x3000, "open-history3",
8, C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN|OPEN_HISTORY|0x4000, "open-history4",
9, C_1FUNC, 64 /* EdSaveFile */, SAV_QUIT , "quit-file", 
10, C_1FUNC, 64 /* EdSaveFile */, SAV_QUIT|SAV_SAVE, "save-file-and-close", 
11, C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE|SAV_AS, "save-file-as", 
12, C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE , "save-file", 
13, C_0FUNC, 7 /* EdBlockRead */, 0 , "read-block", 
14, C_0FUNC, 8 /* EdBlockWrite */, 0 , "save-block", 
15, C_1FUNC, 61 /* EdExitAndSave */, 0 , "exit-edit", 
16, C_1FUNC, 62 /* EdExit */, 0 , "quit-edit", 
17, C_0FUNC, 47 /* EdFind */, 0 , "find-string", 
18, C_0FUNC, 48 /* EdReplace */, 0 , "replace-string", 
19, C_1FUNC, 49 /* EdFindAgain */, 0 , "find-again", 
20, C_1FUNC, 49 /* EdFindAgain */, 1 , "find-again-forward", 
21, C_1FUNC, 49 /* EdFindAgain */, -1 , "find-again-backward", 
22, C_1FUNC, 84 /* EdFindWordCursor */, 1 , "find-word-forward", 
23, C_0FUNC, 83 /* EdFindTagCursor */, 0 , "find-tag-under-cursor", 
24, C_1FUNC, 84 /* EdFindWordCursor */, -1 , "find-word-back", 
25, C_0FUNC, 81 /* EdFindFileCursor */, 0 , "find-file-under-cursor", 
26, C_0FUNC, 46 /* EdFindInFileList */, 0 , "find-in-filelist", 
27, C_1FUNC, 80 /* EdFindTag */, 0 , "find-tag", 
28, C_0FUNC, 54 /* EdMarkSet */, 0 , "set-mark", 
29, C_0FUNC, 55 /* EdMarkGoto */, 0 , "goto-mark", 
30, C_0FUNC, 53 /* EdGotoLine */, 0 , "goto-line", 
31, C_1FUNC, 92 /* fm_gotoLastPosition */, MTE_AUTO_LAST_SEARCH, "goto-last-pos", 
32, C_1FUNC, 92 /* fm_gotoLastPosition */, MTE_AUTO_LAST_INSERT , "goto-last-insertion-pos", 
33, C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_START, "mark-block-start", 
34, C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_END , "mark-block-end", 
35, C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_ALL , "mark-all", 
36, C_0FUNC, 11 /* bl_hideSelectionInCurrentWindow */, 0 , "hide-block-marks", 
37, C_0FUNC, 5 /* EdBlockFindStart */, 0 , "find-block-start", 
38, C_0FUNC, 4 /* EdBlockFindEnd */, 0 , "find-block-end", 
39, C_1FUNC, 9 /* bl_cutOrCopy */, CUT_DELETE, "cut-block",
40, C_1FUNC, 9 /* bl_cutOrCopy */, CUT_QUERYID|CUT_DELETE, "cut-to-named-buffer",
41, C_1FUNC, 9 /* bl_cutOrCopy */, CUT_QUERYID, "copy-to-named-buffer", 
42, C_1FUNC, 9 /* bl_cutOrCopy */, 0, "copy-to-clipboard", 
43, C_1FUNC, 10 /* EdBlockPaste */, PASTE_QUERYID, "paste-named-buffer", 
44, C_1FUNC, 10 /* EdBlockPaste */, PASTE_CLIP, "paste-clipboard", 
45, C_1FUNC, 10 /* EdBlockPaste */, PASTE_UNDO, "paste-trash", 
46, C_1FUNC, 82 /* xref_navigateSearchErrorList */, LIST_CURR, "errorlist-current-line",
47, C_1FUNC, 3 /* EdBlockDelete */, 1 , "delete-block",
48, C_0FUNC, 2 /* EdBlockCopy */, 0 , "copy-block", 
49, C_0FUNC, 6 /* EdBlockMove */, 0 , "move-block", 
50, C_0FUNC, 13 /* bl_cutLines */, 0 , "cut-lines", 
51, C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE|WM_COLUMN_SELECTION, "toggle-column-selection", 
52, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWCONTROL, "toggle-show-control", 
53, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWRULER, "toggle-show-ruler", 
54, C_0FUNC, 114 /* EdPrinterLayout */, 0 , "dialog-printer-layout", 
55, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWHEX, "toggle-hex-modus", 
56, C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE|WM_DELETE_MULTIPLE_SPACES, "delete-multiple-spaces", 
57, C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE|WM_INSERT, "toggle-insert-mode", 
58, C_0FUNC, 59 /* EdOptionSet */, 0 , "set-options", 
59, C_0FUNC, 18 /* EdFormatText */, 0 , "format-text", 
60, C_1FUNC, 31 /* EdReplaceTabs */, 0 , "compress-tabs", 
61, C_1FUNC, 31 /* EdReplaceTabs */, 1 , "expand-tabs", 
62, C_0FUNC, 93 /* EdAlignText */, 0 , "align-text", 
63, C_1FUNC, 87 /* EdRangeShift */, 1 , "shift-range-right", 
64, C_1FUNC, 87 /* EdRangeShift */, -1 , "shift-range-left", 
65, C_0FUNC, 69 /* EdSort */, 0 , "sort-text", 
66, C_1FUNC, 89 /* EdFilesCompare */, LIST_NEXT , "next-difference", 
67, C_1FUNC, 60 /* EdPrint */, PRT_CURRWI, "print-window", 
68, C_1FUNC, 60 /* EdPrint */, PRT_CURRBLK, "print-block", 
69, C_1FUNC, 60 /* EdPrint */, PRT_FILE , "print-file", 
70, C_0FUNC, 66 /* EdCommandExecute */, 0 , "execute-command", 
71, C_0FUNC, 28 /* EdTagfileRead */, 0 , "read-tagfile", 
72, C_0FUNC, 21 /* EdSearchListRead */, 0 , "read-search-list", 
73, C_1FUNC, 22 /* EdErrorListRead */, 0 , "read-compiler-errors", 
74, C_0FUNC, 26 /* EdDocMacrosAdd */, 0 , "add-doc-macros", 
75, C_0FUNC, 45 /* EdMacroRecord */, 0 , "record-macro", 
76, C_0FUNC, 24 /* EdMacrosEdit */, 0 , "dialog-macros", 
77, C_1FUNC, 27 /* macro_readWriteWithFileSelection */, 1 , "write-macros", 
78, C_1FUNC, 27 /* macro_readWriteWithFileSelection */, 0 , "read-macros", 
79, C_0FUNC, 29 /* EdSetup */, 0 , "save-options", 
80, C_0FUNC, 109 /* EdConfigureIcons */, 0 , "configure-icons", 
81, C_0FUNC, 75 /* dlg_configureEditorModes */, 0 , "dialog-display-mode", 
82, C_0FUNC, 74 /* EdDlgWorkMode */, 0 , "dialog-work-mode", 
83, C_0FUNC, 76 /* EdDlgCursTabs */, 0 , "dialog-text-cursor", 
84, C_0FUNC, 77 /* EdDlgModeVals */, 0 , "dialog-macro-bindings", 
85, C_1FUNC, 23 /* doctypes_readWriteDocumentDescriptor */, 1 , "save-ruler", 
86, C_1FUNC, 23 /* doctypes_readWriteDocumentDescriptor */, 0 , "read-ruler", 
87, C_0FUNC, 71 /* EdInfoFiles */, 0 , "info-to-file", 
88, C_0FUNC, 63 /* EdCloseAll */, 0 , "close-all-windows", 
89, C_1FUNC, 85 /* EdWinArrange */, WIN_ICONARRANGE, "arrange-icons", 
90, C_1FUNC, 85 /* EdWinArrange */, WIN_CASCADE, "cascade-windows", 
91, C_1FUNC, 85 /* EdWinArrange */, WIN_TILE , "tile-windows", 
CMD_HELP_README, C_1FUNC, 110 /* EdHelpContext */, IDM_HLPREADME, "help-readme",
CMD_HELP_OVERVIEW, C_1FUNC, 110 /* EdHelpContext */, IDM_HLPOVERVIEW, "help-overview",
CMD_HELP_ON_KEYS, C_1FUNC, 110 /* EdHelpContext */, IDM_HLPONKEYS, "help-on-keys",
CMD_HELP_RELEASE_NOTES, C_1FUNC, 110 /* EdHelpContext */, IDM_HLPRELEASENOTES, "help-release-notes",
CMD_HELP_MANUAL_TOC, C_1FUNC, 110 /* EdHelpContext */, IDM_HLP_MANUAL_TOC, "help-manual-toc",
CMD_SHOW_COPYRIGHT, C_0FUNC, 1 /* EdAbout */, 0 , "show-copyright", 
CMD_KEYCODE_INSERT, C_0FUNC, 16 /* EdKeycodeInsert */, 0 , "keycode-insert", 
99, C_0FUNC, 74 /* evaluate_evaluateSelection */, 0 , "evaluate-selection", 
100, C_0FUNC, 76 /* mainframe_toggleFullScreen */, 0, "toggle-full-screen", 
101, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE | SHOWWYSIWYG, "toggle-show-wysiwyg",
102, C_1FUNC, 86 /* EdWindowRegSet */, 3 , "unused",
103, C_1FUNC, 86 /* EdWindowRegSet */, 4 , "unused", 
104, C_1FUNC, 86 /* EdWindowRegSet */, 5 , "unused", 
105, C_1FUNC, 85 /* EdWinArrange */, WIN_FULL , "set-win-zoomed", 
106, C_1FUNC, 85 /* ManageDocks */, MD_ADD_HORIZONTAL, "tile-docks-horizontally",
107, C_1FUNC, 85 /* ManageDocks */, MD_ADD_VERTICAL, "tile-docks-vertically",
108, C_1FUNC, 86 /* xref_navigateSearchErrorList */, LIST_CURR, "errorlist-click-line",
109, C_1FUNC, 56 /* menu_openContextMenu */, 0, "open-context-menu",
110, C_1FUNC, 77 /* EdFindOnInternet */, 0, "search-on-internet", 
111, C_1FUNC, 85 /* EdWinArrange */, 5 , "unused", 
112, C_1FUNC, 65 /* EdSelectWindow */, 1 , "select-window-1", 
113, C_1FUNC, 65 /* EdSelectWindow */, 2 , "select-window-2", 
114, C_1FUNC, 65 /* EdSelectWindow */, 3 , "select-window-3", 
115, C_1FUNC, 65 /* EdSelectWindow */, 4 , "select-window-4", 
116, C_1FUNC, 65 /* EdSelectWindow */, 5 , "select-window-5", 
117, C_1FUNC, 65 /* EdSelectWindow */, 6 , "select-window-6", 
118, C_1FUNC, 65 /* EdSelectWindow */, -1 , "select-previous-window", 
119, C_1FUNC, 125 /* windowselector_showWindowList */, 0, "cycle-window", 
120, C_1FUNC, 73 /* edit_convertCharacterCase */, CC_TOGGLE, "char-up-low", 
121, C_1FUNC, 70 /* EdLinesShift */, -1 , "shift-line-left", 
122, C_1FUNC, 70 /* EdLinesShift */, 1 , "shift-line-right", 
123, C_0FUNC, 50 /* EdReplaceAgain */, 0 , "replace-again", 
124, C_1FUNC, 82 /* xref_navigateSearchErrorList */, LIST_NEXT , "errorlist-next", 
125, C_1FUNC, 82 /* xref_navigateSearchErrorList */, LIST_END , "errorlist-end", 
126, C_1FUNC, 82 /* xref_navigateSearchErrorList */, LIST_PREV , "errorlist-previous", 
127, C_1FUNC, 82 /* xref_navigateSearchErrorList */, LIST_START, "errorlist-start", 
128, C_0FUNC, 72 /* EdShowMatch */, 0 , "check-brackets", 
129, C_0FUNC, 51 /* EdCharControlInsert */, 0 , "insert-char-with-dialog", 
130, C_1FUNC, 68 /* EdShiftBetweenBrackets */, -1 , "shift-between-brackets-left", 
131, C_1FUNC, 68 /* EdShiftBetweenBrackets */, 1 , "shift-between-brackets-right", 
132, C_1FUNC, 17 /* EdCharInsert */, 127 , "delete-char", 
133, C_1FUNC, 41 /* EdCharDelete */, MOT_TOEND , "delete-to-eol", 
134, C_1FUNC, 41 /* EdCharDelete */, MOT_SPACE, "delete-word", 
135, C_1FUNC, 41 /* EdCharDelete */, MOT_UNTILC, "delete-to-next-char", 
136, C_1FUNC, 41 /* EdCharDelete */, -MOT_SPACE, "delete-back-white", 
137, C_1FUNC, 41 /* EdCharDelete */, MOT_WORD, "delete-to-white", 
138, C_1FUNC, 41 /* EdCharDelete */, -MOT_TOEND, "delete-to-sol", 
139, C_1FUNC, 41 /* EdCharDelete */, -MOT_SPACE, "delete-back-word", 
140, C_1FUNC, 41 /* EdCharDelete */, -MOT_UNTILC, "delete-until-previous-char", 
141, C_1FUNC, 17 /* EdCharInsert */, 13 , "split-line", 
142, C_1FUNC, 32 /* EdLineSplit */, RET_PLUS , "split-line-indent-plus", 
143, C_1FUNC, 32 /* EdLineSplit */, RET_MINUS , "split-line-indent-minus", 
144, C_0FUNC, 57 /* EdLinesJoin */, 0 , "join-lines", 
145, C_1FUNC, 39 /* EdCursorUp */, MOT_SINGLE, "cursor-up-line", 
146, C_1FUNC, 39 /* EdCursorUp */, MOT_TOEND , "cursor-top-of-page", 
147, C_1FUNC, 39 /* EdCursorUp */, MOT_WORD , "cursor-back-page", 
148, C_1FUNC, 40 /* EdCursorDown */, MOT_SINGLE, "cursor-down-line", 
149, C_1FUNC, 40 /* EdCursorDown */, MOT_TOEND , "cursor-bottom-of-page", 
150, C_1FUNC, 40 /* EdCursorDown */, MOT_WORD , "cursor-down-page", 
151, C_1FUNC, 37 /* EdCursorRight */, MOT_SINGLE, "cursor-right-char", 
152, C_1FUNC, 37 /* EdCursorRight */, MOT_TOEND , "cursor-eol", 
153, C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE, "cursor-right-word", 
154, C_1FUNC, 37 /* EdCursorRight */, MOT_UNTILC, "cursor-until-char", 
155, C_1FUNC, 38 /* EdCursorLeft */, MOT_SINGLE, "cursor-left-char", 
156, C_1FUNC, 38 /* EdCursorLeft */, MOT_TOEND , "cursor-sol", 
157, C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE, "cursor-left-word", 
158, C_1FUNC, 38 /* EdCursorLeft */, MOT_UNTILC, "cursor-back-to-char", 
159, C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE , "cursor-to-space", 
160, C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE , "cursor-back-to-space", 
161, C_1FUNC, 39 /* EdCursorUp */, MOT_FILE , "cursor-home", 
162, C_1FUNC, 40 /* EdCursorDown */, MOT_FILE , "cursor-eof", 
163, C_1FUNC, 19 /* edit_insertLine */, 0 , "insert-line-follow", 
164, C_1FUNC, 14 /* EdLineDelete */, 0 , "delete-line-stay", 
165, C_1FUNC, 14 /* EdLineDelete */, CUT_APPND , "delete-line-append", 
166, C_1FUNC, 14 /* EdLineDelete */, 1 , "delete-line-follow", 
167, C_1FUNC, 0 /* EdFileAbandon */, 0 , "abandon-file", 
168, C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE|SAV_QUIT, "save-and-close", 
169, C_1FUNC, 19 /* edit_insertLine */, 1 , "insert-line-stay", 
170, C_0FUNC, 25 /* EdDocMacrosEdit */, 0 , "edit-doc-macros", 
171, C_0FUNC, 15 /* bl_destroyAll */, 0 , "delete-named-buffers", 
172, C_1FUNC, 20 /* edit_performLineFlagOperation */, MLN_DELETE, "delete-marked-lines", 
173, C_0FUNC, 30 /* EdSetMultiplier */, 0 , "set-multiplikator", 
174, C_0FUNC, 43 /* codecomplete_showSuggestionWindow */, 0 , "escape-makro", 
175, C_0FUNC, 42 /* fkey_keyModifierStateChanged */, 0, "switch-fkeys", 
176, C_0FUNC, 113 /* EdDocTypes */, 0 , "dialog-doc-types", 
177, C_0FUNC, 42 /* unused */, 0, "unused", 
178, C_1FUNC, 44 /* macro_executeMacroByIndex */, MAC_AUTO , "re-insert", 
179, C_0FUNC, 45 /* unused */, 0 , "unused", 
180, C_0FUNC, 88 /* EdUndo */, 0 , "undo", 
181, C_1FUNC, 20 /* edit_performLineFlagOperation */, MLN_TOGGLE, "toggle-line-marks", 
182, C_1FUNC, 85 /* EdWinArrange */, WIN_DESKICON, "iconize-edit", 
183, C_1FUNC, 85 /* EdWinArrange */, WIN_ICONIZED, "iconize-window", 
184, C_1FUNC, 89 /* EdFilesCompare */, LIST_PREV , "last-difference", 
185, C_1FUNC, 90 /* EdScrollScreen */, MOT_SINGLE, "scroll-up-line", 
186, C_1FUNC, 90 /* EdScrollScreen */, -MOT_SINGLE, "scroll-down-line", 
187, C_1FUNC, 90 /* EdScrollScreen */, MOT_PAGE , "scroll-up-page", 
188, C_1FUNC, 90 /* EdScrollScreen */, -MOT_PAGE , "scroll-down-page", 
189, C_1FUNC, 40 /* EdCursorDown */, MOT_CENTER, "cursor-center-page", 
190, C_1FUNC, 91 /* EdScrollCursor */, MOT_SINGLE, "scroll2-up-line", 
191, C_1FUNC, 91 /* EdScrollCursor */, -MOT_SINGLE, "scroll2-down-line", 
192, C_1FUNC, 91 /* EdScrollCursor */, MOT_CENTER, "scroll-center-page", 
193, C_1FUNC, 20 /* edit_performLineFlagOperation */, MLN_JOIN , "join-marked-lines", 
194, C_0FUNC, 25 /* EdDocMacrosEdit */, 0 , "edit-local-doc-macros", 
195, C_1FUNC, 52 /* fm_gotoNextPosition */, MTE_AUTO_LAST_INSERT, "undefined", 
196, C_1FUNC, 60 /* EdPrint */, PRT_CLIP , "print-clipboard", 
197, C_1FUNC, 60 /* EdPrint */, PRT_TRASH , "print-trash", 
198, C_1FUNC, 10 /* EdBlockPaste */, PASTE_ICON|PASTE_UNDO, "paste-undo", 
199, C_1FUNC, 10 /* EdBlockPaste */, PASTE_ICON|PASTE_CLIP, "paste-clip-icon", 
200, C_0FUNC, 67 /* EdExecute */, 0 , "icon-execute", 
201, C_0FUNC, 94 /* function_unused */, 0 , "remove-icon", 
202, C_1FUNC, 99 /* EdMousePositionUngrabbed */, 1 , "cursor-mouse-goto", 
203, C_1FUNC, 97 /* EdMouseMoveText */, 0 , "drag-copy-text", 
204, C_1FUNC, 97 /* EdMouseMoveText */, 1 , "drag-move-text", 
205, C_1FUNC, 98 /* EdMouseSelectLines */, 1 , "mouse-select-lines", 
206, C_1FUNC, 98 /* EdMouseSelectLines */, 0 , "mouse-unselect-lines", 
207, C_1FUNC, 44 /* macro_executeMacroByIndex */, MAC_LASTREC, "play-last-macro", 
208, C_1FUNC, 95 /* EdBlockMouseMark */, 0 , "mouse-mark-block", 
209, C_1FUNC, 96 /* EdMouseMarkParts */, MOT_TOEND , "mouse-mark-line", 
210, C_1FUNC, 96 /* EdMouseMarkParts */, MOT_WORD , "mouse-mark-word", 
211, C_1FUNC, 96 /* EdMouseMarkParts */, MOT_SPACE , "mouse-mark-to-space", 
212, C_1FUNC, 96 /* EdMouseMarkParts */, MOT_PGRPH , "mouse-mark-paragraph", 
213, C_1FUNC, 95 /* EdBlockMouseMark */, 0, "mouse-update-block", 
214, C_1FUNC, 111 /* EdListBindings */, LIST_MACROS, "macro-list", 
215, C_1FUNC, 111 /* EdListBindings */, LIST_KEYS , "key-list", 
216, C_1FUNC, 111 /* EdListBindings */, LIST_MICE , "mouse-list", 
217, C_1FUNC, 112 /* EdCompileMacros */, 1 , "compile-macros", 
218, C_1FUNC, 17 /* EdCharInsert */, 10 , "split-line-soft", 
219, C_1FUNC, 117 /* EdShowClipboard */, 0 , "show-std-clip", 
220, C_1FUNC, 3 /* EdBlockDelete */, 0 , "erase-block", 
221, C_1FUNC, 111 /* EdListBindings */, LIST_MENUS, "menu-list", 
222, C_0FUNC, 120 /* EdRedo */, 0, "redo", 
223, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE | SHOWLINENUMBERS, "toggle-show-linenumbers", 
224, C_1FUNC, 38 /* EdCursorLeft */, MOT_SINGLE|MOT_XTNDBLOCK, "select-left", 
225, C_1FUNC, 38 /* EdCursorLeft */, MOT_TOEND | MOT_XTNDBLOCK, "select-left-to-start", 
226, C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE | MOT_XTNDBLOCK, "select-left-word", 
227, C_1FUNC, 37 /* EdCursorRight */, MOT_SINGLE | MOT_XTNDBLOCK, "select-right", 
228, C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE | MOT_XTNDBLOCK, "select-right-word", 
229, C_1FUNC, 37 /* EdCursorRight */, MOT_TOEND | MOT_XTNDBLOCK, "select-right-to-end", 
230, C_1FUNC, 39 /* EdCursorUp */, MOT_SINGLE | MOT_XTNDBLOCK, "select-up", 
231, C_1FUNC, 40 /* EdCursorDown */, MOT_SINGLE | MOT_XTNDBLOCK, "select-down", 
232, C_1FUNC, 39 /* EdCursorUp */, MOT_PAGE | MOT_XTNDBLOCK, "select-page-up", 
233, C_1FUNC, 40 /* EdCursorDown */, MOT_PAGE | MOT_XTNDBLOCK, "select-page-down", 
234, C_1FUNC, 121 /* EdSaveAllFiles*/, 0, "save-all-files", 
235, C_1FUNC, 114 /* find_initiateIncrementalSearch */, 0, "search-incrementally", 
236, C_1FUNC, 122 /* ft_cloneWindow */, 0, "clone-window", 
237, C_1FUNC, 123 /* edit_shiftSelection */, 1, "tab-shift-right", 
238, C_1FUNC, 123 /* edit_shiftSelection */, -1, "tab-shift-left", 
239, C_1FUNC, 23 /* ww_zoomWindow */, 1, "zoom-increase", 
240, C_1FUNC, 23 /* ww_zoomWindow */, 0, "zoom-decrease", 
241, C_1FUNC, 124 /* edit_toggle_comment */, -1, "toggle-comment", 
242, C_1FUNC, 52 /* fm_gotoNextPosition */, MTE_AUTO_LAST_SEARCH, "goto-next-pos", 
243, C_1FUNC, 52 /* fm_gotoNextPosition */, MTE_AUTO_LAST_INSERT, "goto-next-insertion-pos", 
244, C_1FUNC, 20 /* edit_performLineFlagOperation */, MLN_MAKESOFT, "use-linux-lineends", 
245, C_1FUNC, 20 /* edit_performLineFlagOperation */, MLN_MAKEHARD, "use-windows-lineends", 
246, C_1FUNC, 73 /* edit_convertCharacterCase */, CC_UPPER, "char-to-upper", 
247, C_1FUNC, 73 /* edit_convertCharacterCase */, CC_LOWER, "char-to-lower", 
248, C_1FUNC, 126 /* compare_navigate*/, 1, "compare-navigate-next",
249, C_1FUNC, 126 /* compare_navigate*/, -1, "compare-navigate-previous",
250, C_0FUNC, 127 /* compare_clear*/, -1, "compare-clear",
251, C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE | WM_LINE_SELECTION, "toggle-line-selection",
252, C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE | SHOW_SYNTAX_HIGHLIGHT, "toggle-syntax-highlighting",
253, C_1FUNC, 128 /* bl_moveSelectionUpDown */, -1, "move-selection-up",
254, C_1FUNC, 128 /* bl_moveSelectionUpDown */, 1, "move-selection-down"
// no more commands can be added: maximum is currently 255.
};

char _recorder[RECORDERSPACE];
int _lcomseq = 1332;
int _ncmdseq = sizeof(_cmdseqtab)/sizeof(_cmdseqtab[0]);

