#include <windows.h>
#include "edfuncs.h"
#include "functab.h"
#include "pksedit.h"
#include "edierror.h"
#include "publicapi.h"
#include "findandreplace.h"
#include "iccall.h"

extern int
EdFileAbandon(), EdAbout(long ), EdBlockCopy(long ), EdBlockDelete(long ),
EdBlockFindEnd(long ), EdBlockFindStart(long ), EdBlockMove(long ), EdBlockRead(long ),
EdBlockWrite(long ), EdBlockCut(long ), EdBlockPaste(long ), EdBlockHide(long ),
EdSyncSelectionWithCaret(long ), EdLinesYank(long ), EdLineDelete(long ), EdBufferFree(long ),
EdKeycodeInsert(long ), EdCharInsert(long ), EdFormatText(long ), EdLineInsert(long ),
EdMarkedLineOp(long ), EdSearchListRead(long ), EdErrorListRead(long ), doctypes_readWriteDocumentDescriptor(long ),
EdMacrosEdit(long ), EdDocMacrosEdit(long ), EdDocMacrosAdd(long ), macro_readWriteWithFileSelection(long ),
EdTagfileRead(long ), EdSetup(long ), EdSetMultiplier(long ), EdReplaceTabs(long ),
EdLineSplit(long ), EdParaGotoBegin(long ),
EdParaGotoEnd(long ), EdCharDelete(long ), fkey_keyModifierStateChanged(long ), EdMacroEscape(long ),
macro_executeMacroByIndex(long ), EdMacroRecord(long ), EdFindInFileList(long ), EdFind(long ),
EdReplace(long ), EdFindAgain(long ), EdReplaceAgain(long ), EdCharControlInsert(long ),
EdGotoLastPos(long ), EdGotoLine(long ), EdMarkSet(long ), EdMarkGoto(long ),
EdHelp(long ), EdLinesJoin(long ), EdEditFile(long ), EdOptionSet(long ),
EdPrint(long ), EdExitAndSave(long ), EdExit(long ), EdCloseAll(long ),
EdSaveFile(int ), EdSelectWindow(long ), EdCommandExecute(long ), EdExecute(long ),
EdShiftBetweenBrackets(long ), EdSort(long ), EdLinesShift(long ), EdInfoFiles(long ),
EdShowMatch(long ), EdCharUpToLow(long ), EdDlgWorkMode(long ), EdDlgDispMode(long ),
EdDlgCursTabs(long ), EdDlgModeVals(long ), EdOptionToggle(long ), EdPasteString(long ),
EdFindTag(long ), EdFindFileCursor(long ), EdErrorNext(long ), EdFindTagCursor(long ),
EdFindWordCursor(long ), EdWinArrange(long ), EdWindowRegSet(long ), EdRangeShift(long ),
EdUndo(long ), EdRedo(long), EdFilesCompare(long ), EdScrollScreen(long ), EdScrollCursor(long ),
EdGotoPreviousTag(long ), EdAlignText(long ), ic_closeIconWindow(long ), EdBlockMouseMark(long ),
EdMouseMarkParts(long ), EdMouseMoveText(long ), EdMouseSelectLines(long ), EdMousePositionUngrabbed(long ),
EdAlert(long ), error_displayAlertBoxWithOptions(long ), EdPromptAssign(long ), EdFormatPrint(long ),
EdGetSelectedText(long ), EdHideLines(long ), EdUnHideLine(long ), EdStringSubstitute(long ),
EdExpandAbbreviation(long ), EdConfigureIcons(long ), EdHelpContext(long ), EdListBindings(long ),
EdCompileMacros(long ), EdDocTypes(long ), EdIsDefined(long ), ft_cloneWindow(),
EdCallWinHelp(long ), EdShowClipboard(long ), EdSaveAllFiles(), EdMenuTrackPopup(long ), EdBlockXtndMode(long );

EDFUNC _edfunctab[] = {
	EdFileAbandon , '!',	EW_NEEDSCURRF | 0,		
	EdAbout       , '!',	0,
	EdBlockCopy   , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,
	EdBlockDelete , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,
	EdBlockFindEnd, '!',	EW_NEEDSCURRF | EW_NEEDSBLK | 0,
	EdBlockFindStart, '!',	EW_NEEDSCURRF | EW_NEEDSBLK | 0,
	EdBlockMove   , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_NEEDSBLK | 0,
	EdBlockRead   , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
	EdBlockWrite  , '!',	EW_NEEDSCURRF | EW_NEEDSBLK | 0,
	EdBlockCut    , '!',	EW_NEEDSCURRF | EW_NEEDSBLK | 0,
	EdBlockPaste  , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
	EdBlockHide   , '!',	EW_NEEDSCURRF | 0,
	EdSyncSelectionWithCaret   , '!',	EW_NEEDSCURRF | 0,
	EdLinesYank   , '!',	EW_NEEDSCURRF | EW_MULTI | 0,
	EdLineDelete  , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
	EdBufferFree  , '!',	0,
	EdKeycodeInsert, '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
	EdCharInsert  , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_CCASH | 0,
	EdFormatText  , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
	EdLineInsert  , '!',	EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdMarkedLineOp, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdSearchListRead, '!', EW_HASFORM | 0,
EdErrorListRead, '!', 0,
doctypes_readWriteDocumentDescriptor, '!', EW_NEEDSCURRF | EW_HASFORM | 0,
EdMacrosEdit, '!', EW_MULTI | 0,
EdDocMacrosEdit, '!', 0,
EdDocMacrosAdd, '!', EW_HASFORM | 0,
macro_readWriteWithFileSelection, '!', EW_HASFORM | 0,
EdTagfileRead, '!', EW_HASFORM | 0,
EdSetup, '!', 0,
EdSetMultiplier, '!', 0,
EdReplaceTabs, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdLineSplit, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdChapterGotoBegin, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdChapterGotoEnd, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdParaGotoBegin, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdParaGotoEnd, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdCursorRight, '!', EW_NEEDSCURRF | 0,
EdCursorLeft, '!', EW_NEEDSCURRF | 0,
EdCursorUp, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdCursorDown, '!', EW_NEEDSCURRF | EW_MULTI | 0,
EdCharDelete, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
fkey_keyModifierStateChanged, '!', 0,
EdMacroEscape, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_HASFORM | 0,
macro_executeMacroByIndex, '!', EW_NOCASH | EW_CCASH | 0,
EdMacroRecord, '!', EW_NOCASH | 0,
EdFindInFileList, '!', EW_HASFORM | 0,
EdFind, '!', EW_NEEDSCURRF | EW_HASFORM | 0,
EdReplace, '!', EW_MODIFY | EW_NEEDSCURRF | EW_HASFORM | 0,
EdFindAgain, '!', EW_NEEDSCURRF | 0,
EdReplaceAgain, '!', EW_MODIFY | EW_NEEDSCURRF | 0,
EdCharControlInsert, '!', EW_MODIFY | EW_NEEDSCURRF | EW_HASFORM | EW_CCASH | 0,
EdGotoLastPos, '!', EW_NEEDSCURRF | 0,
EdGotoLine, '!', EW_NEEDSCURRF | 0,
EdMarkSet, '!', EW_NEEDSCURRF | EW_HASFORM | 0,
EdMarkGoto, '!', EW_NEEDSCURRF | EW_HASFORM | 0,
EdHelp, '!', 0,
EdLinesJoin, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdEditFile, '!', EW_HASFORM | 0,
EdOptionSet, '!', EW_HASFORM | 0,
EdPrint, '!', 0,
EdExitAndSave, '!', 0,
EdExit, '!', 0,
EdCloseAll, '!', 0,
EdSaveFile, '!', EW_NEEDSCURRF | 0,
EdSelectWindow, '!', 0,
EdCommandExecute, '!', EW_HASFORM | 0,
EdExecute, '!', EW_HASFORM | 0,
EdShiftBetweenBrackets, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdSort, '!', EW_MODIFY | EW_NEEDSCURRF | 0,
EdLinesShift, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | EW_MULTI | 0,
EdInfoFiles, '!', 0,
EdShowMatch, '!', EW_NEEDSCURRF | 0,
EdCharUpToLow, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdDlgWorkMode, '!', EW_NEEDSCURRF | 0,
EdDlgDispMode, '!', EW_NEEDSCURRF | 0,
EdDlgCursTabs, '!', EW_NEEDSCURRF | 0,
EdDlgModeVals, '!', EW_NEEDSCURRF | 0,
EdOptionToggle, '!', EW_NEEDSCURRF | 0,
EdPasteString, '!', EW_NEEDSCURRF | 0,
EdFindTag, '!', EW_HASFORM | 0,
EdFindFileCursor, '!', EW_NEEDSCURRF | 0,
EdErrorNext, '!', 0,
EdFindTagCursor, '!', EW_NEEDSCURRF | 0,
EdFindWordCursor, '!', EW_NEEDSCURRF | 0,
EdWinArrange, '!', 0,
EdWindowRegSet, '!', EW_NEEDSCURRF | 0,
EdRangeShift, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdUndo, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDO_AVAILABLE,
EdFilesCompare, '!', EW_NEEDSCURRF | 0,
EdScrollScreen, '!', EW_NEEDSCURRF | 0,
EdScrollCursor, '!', EW_NEEDSCURRF | 0,
EdGotoPreviousTag, '!', 0,
EdAlignText, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
ic_closeIconWindow, '!', 0,
EdBlockMouseMark, '!', EW_NEEDSCURRF | 0,
EdMouseMarkParts, '!', EW_NEEDSCURRF | 0,
EdMouseMoveText, '!', EW_NEEDSCURRF | 0,
EdMouseSelectLines, '!', EW_NEEDSCURRF | 0,
EdMousePositionUngrabbed, '!', EW_NEEDSCURRF | 0,
EdAlert, '!', 0,
error_displayAlertBoxWithOptions, '!', 0,
EdPromptAssign, '!', 0,
EdFormatPrint, '!', 0,
EdGetSelectedText, '!', 0,
EdHideLines, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdUnHideLine, '!', EW_MODIFY | EW_NEEDSCURRF | EW_UNDOFLSH | 0,
EdStringSubstitute, '!', 0,
EdExpandAbbreviation, '!', 0,
EdConfigureIcons, '!', 0,
EdHelpContext, '!', 0,
EdListBindings, '!', 0,
EdCompileMacros, '!', EW_NEEDSCURRF | 0,
EdDocTypes, '!', 0,
find_initiateIncrementalSearch, '!', EW_NEEDSCURRF,
EdIsDefined, '!', 0,
EdCallWinHelp, '!', 0,
EdShowClipboard, '!', 0,
EdMenuTrackPopup, '!', EW_NEEDSCURRF | 0,
EdBlockXtndMode, '!', EW_NEEDSCURRF | 0,
EdRedo, '!', EW_MODIFY | EW_NEEDSCURRF | EW_REDO_AVAILABLE,
EdSaveAllFiles, '!', EW_NEEDSCURRF | 0,
ft_cloneWindow, '!', EW_NEEDSCURRF,
};

int _nfuncs = sizeof(_edfunctab)/sizeof(_edfunctab[0]);
MENUBIND _menutab[] = {
MNEWFILE	,1 ,
MOPENF	,0 ,
MOPENLIN	,3 ,
MQUITF	,9 ,
MSAVEF	,10,
MSAVEAS	,11,
MSAVERES	,12,
MREADF	,13,
MWRITEF	,14,
MABANDON	,167,
MCLONEWINDOW, 236,
MSAVEALL	,15,
MEXIT	,16,
IDM_HISTORY	,4 ,
IDM_HISTORY1	,5 ,
IDM_HISTORY2	,6 ,
IDM_HISTORY3	,7 ,
IDM_HISTORY4	,8 ,
IDM_UNDO	,180,
IDM_REDO, 222,
IDM_DOAGAIN	,178,
MFIND	,17,
MREPLACE	,18,
MFAGAIN	,19,
MEDIFLIS	,26,
MSHOWTAG	,27,
MSETMARK	,28,
MGOTOMAR	,29,
MSAVEALL_NO_EXIT, 234,
MGOTOLN	,30,
MLASTPOS	,31,
MFLASTP	,32,
MTMSTART	,33,
MTMEND	,34,
MTMHIDE	,36,
MTMFSTAR	,37,
MTMFEND	,38,
MTCUT	,39,
MTPASTE	,44,
IDM_ERASEBLOCK	,220,
MTDEL	,47,
MTCOPY	,48,
MTMOVE	,49,
MCOLFORM	,51,
MFORMAT	,59,
MCOMTABS	,60,
MEXPTABS	,61,
MENALIGN	,62,
MSHFTRIG	,63,
MSHFTLEF	,64,
MMSORT	,65,
MENDIFF	,66,
IDM_PRINTTEXT	,67,
IDM_PRINTBLOCK	,68,
IDM_PRINTFILE	,69,
MEXEC	,70,
MREADTAG	,71,
MREADSTE	,72,
MREADCMP	,73,
MOPTION	,58,
MSAVESET	,79,
MENEX	,80,
MMRECORDER	,75,
MMACEDIT	,76,
IDM_COMPILEMACROS	,217,
IDM_MACROLIST	,214,
IDM_KEYLIST	,215,
IDM_MOUSELIST	,216,
IDM_MENULIST	,221,
MREADSEQ	,78,
MWRSEQ	,77,
IDM_DOCTYPES	,176,
IDM_DISPMODE	,81,
IDM_WORKMODE	,82,
IDM_CURSTABS	,83,
IDM_MODEVALS	,84,
MEDITDOCMAC	,170,
MADDDOCMAC	,74,
MMSHOWCO	,52,
MMSHOWLI	,53,
MMSTATHE	,55,
MMSHOWAT	,56,
MMSHOWLINENUMBERS ,223,
MMWRITE	,85,
MMREAD	,86,
IDM_INFOFILE	,87,
IDM_CLOSEALL	,88,
IDM_ARRANGE	,89,
IDM_CASCADE	,90,
IDM_TILE	,91,
IDM_HLPONHLP	,92,
IDM_HLPONMENUS	,93,
IDM_HLPONKEYS	,94,
IDM_HLPONDESKTOP	,95,
IDM_HLPINDEX	,96,
IDM_ABOUT	,97
};

int _nmenus = sizeof(_menutab) / sizeof(_menutab[0]);

ICONBIND _ictab[] = {
ICID_TRASH,	ICID_UNDO,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_EXEC,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_DIR,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_PRINT,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_EDIT,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_FILE,	IPCF_DROPHWND, 201,
ICID_TRASH,	ICID_CLIP,	IPCF_NONE, 171,
ICID_EXEC,	ICACT_DCLICKED,	IPCF_USERDEF, 200,
ICID_DIR,	ICACT_DCLICKED,	IPCF_SRCSTRING1, 2 ,
ICID_FILE,	ICACT_DCLICKED,	IPCF_SRCSTRING1, 1 ,
ICID_CLIP,	ICACT_TEXTBLOCK,	IPCF_SRCCHAR, 39,
ICID_CLIP,	ICACT_DCLICKED,	IPCF_SRCCHAR, 219,
ICID_UNDO,	ICACT_DCLICKED,	IPCF_NONE, 180,
ICID_TRASH,	ICACT_TEXTBLOCK,	IPCF_NONE, 47,
ICID_EDIT,	ICID_CLIP,	IPCF_DROPCHAR, 199,
ICID_EDIT,	ICID_TRASH,	IPCF_DROPCHAR, 198,
ICID_PRINT,	ICID_FILE,	IPCF_DROPSTRING1, 69,
ICID_PRINT,	ICID_TRASH,	IPCF_NONE, 197,
ICID_PRINT,	ICID_CLIP,	IPCF_DROPCHAR, 196,
ICID_PRINT,	ICACT_TEXTBLOCK,	IPCF_NONE, 68,
ICID_PRINT,	ICACT_DCLICKED,	IPCF_NONE, 67,
ICID_PRINT,	ICID_EDIT,	IPCF_NONE, 67
};

int _nicbind = sizeof(_ictab) / sizeof(_ictab[0]);

MOUSEBIND _mousetab[MAXMAPMOUSE] = {
{0x02,0x00,0x02,0,{CMD_CMDSEQ,213}, (char *)0},
{0x02,0x08,0x01,0,{CMD_CMDSEQ,212}, (char *)0},
{0x02,0x07,0x01,0,{CMD_CMDSEQ,211}, (char *)0},
{0x02,0x04,0x01,0,{CMD_CMDSEQ,210}, (char *)0},
{0x02,0x03,0x01,0,{CMD_CMDSEQ,209}, (char *)0},
{0x02,0x00,0x01,0,{CMD_CMDSEQ,208}, (char *)0},
{0x01,0x07,0x02,0,{CMD_CMDSEQ,207}, (char *)0},
{0x01,0x03,0x02,0,{CMD_CMDSEQ,178}, (char *)0},
{0x01,0x00,0x02,0,{CMD_CMDSEQ,23}, (char *)0},
{0x01,0x0b,0x01,MO_FINDCURS,{CMD_CMDSEQ,206}, (char *)0},
{0x01,0x08,0x01,MO_FINDCURS,{CMD_CMDSEQ,205}, (char *)0},
{0x01,0x04,0x01,0,{CMD_CMDSEQ,204}, (char *)0},
{0x01,0x03,0x01,0,{CMD_CMDSEQ,203}, (char *)0},
{0x01,0x00,0x01,0,{CMD_CMDSEQ,208}, (char *)0}
};

int _nmousebind = sizeof(_mousetab)/sizeof(_mousetab[0]);

COMMAND _cmdseqtab[] = {
/* 0 */ C_1FUNC, 58 /* EdEditFile */, 0 , "open-file", "Öffnet eine Datei in einem Bearbeitungsfenster;Datei öffnen",
/* 1 */ C_1FUNC, 58 /* EdEditFile */, OPEN_NOFN , "open-new-file", "Öffnet eine neue Datei;Neue Datei anlegen",
/* 2 */ C_1FUNC, 58 /* EdEditFile */, OPEN_DIRGIVEN, "open-file-dir-given", "Öffnet eine Datei - der voreingestellte Pfad der Dateiauswahl wird als Parameter übergeben",
/* 3 */ C_1FUNC, 58 /* EdEditFile */, OPEN_LINEAL, "open-special", "Öffnet eine Datei mit besonderem Format;Öffnen Spezial",
/* 4 */ C_1FUNC, 58 /* EdEditFile */, OPEN_HISTORY|0x0000, "open-history", "Öffnet die zuletzt geschlossene Datei;Öffnen letzte Datei 1",
/* 5 */ C_1FUNC, 58 /* EdEditFile */, OPEN_HISTORY|0x1000, "open-history1", "Öffnet die vorletzte geschlossene Datei;Öffnen letzte Datei 2",
/* 6 */ C_1FUNC, 58 /* EdEditFile */, OPEN_HISTORY|0x2000, "open-history2", "Öffnet die vorvorletzte geschlossene Datei;Öffnen letzte Datei 3",
/* 7 */ C_1FUNC, 58 /* EdEditFile */, OPEN_HISTORY|0x3000, "open-history3", "Öffnet die drittletzte geschlossene Datei;Öffnen letzte Datei 4",
/* 8 */ C_1FUNC, 58 /* EdEditFile */, OPEN_HISTORY|0x4000, "open-history4", "Öffnet die viertletzte geschlossene Datei;Öffnen letzte Datei 5",
/* 9 */ C_1FUNC, 64 /* EdSaveFile */, SAV_QUIT , "quit-file", "Schließt das Bearbeitungsfenster;Schließen Fenster",
/* 10 */ C_1FUNC, 64 /* EdSaveFile */, SAV_QUIT|SAV_SAVE, "save-file-and-close", "Sichert den Text und schließt das Bearbeitungsfenster;Sichern & Schließen",
/* 11 */ C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE|SAV_AS, "save-file-as", "Sichert den Text unter neuem Namen;Sichern unter",
/* 12 */ C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE , "save-file", "Sichert den Text;Sichern",
/* 13 */ C_0FUNC, 7 /* EdBlockRead */, 0 , "read-block", "Fügt eine Datei an der Cursorposition ein;Lese Block",
/* 14 */ C_0FUNC, 8 /* EdBlockWrite */, 0 , "save-block", "Sichert den markierten Textblock;Sichere Block",
/* 15 */ C_1FUNC, 61 /* EdExitAndSave */, 0 , "exit-edit", "Beendet PKS-EDIT und sichert alle Änderungen;Ende PKS-EDIT",
/* 16 */ C_1FUNC, 62 /* EdExit */, 0 , "quit-edit", "Beendet PKS-EDIT;Quit PKS-EDIT",
/* 17 */ C_0FUNC, 47 /* EdFind */, 0 , "find-string", "Sucht ein Suchmuster;Suchen",
/* 18 */ C_0FUNC, 48 /* EdReplace */, 0 , "replace-string", "Ersetzt ein Suchmuster;Ersetzen",
/* 19 */ C_1FUNC, 49 /* EdFindAgain */, 0 , "find-again", "Wiederholt die letzte Suche;Erneut Suchen",
/* 20 */ C_1FUNC, 49 /* EdFindAgain */, 1 , "find-again-forward", "Wiederholt die letzte Suche vorwärts;Erneut suchen",
/* 21 */ C_1FUNC, 49 /* EdFindAgain */, -1 , "find-again-backward", "Wiederholt die letzte Suche rückwärts;Erneut suchen <-",
/* 22 */ C_1FUNC, 84 /* EdFindWordCursor */, 1 , "find-word-forward", "Sucht das Wort unter dem Cursor;Suche Wort _",
/* 23 */ C_0FUNC, 83 /* EdFindTagCursor */, 0 , "find-tag-under-cursor", "Sucht den Verweis unter dem Cursor;Suche Verweis _",
/* 24 */ C_1FUNC, 84 /* EdFindWordCursor */, -1 , "find-word-back", "Sucht Wort unter dem Cursor rückwärts;Suche Wort rückwärts",
/* 25 */ C_0FUNC, 81 /* EdFindFileCursor */, 0 , "find-file-under-cursor", "Sucht die Datei mit dem Namen des Worts unter dem Cursor;Suche Datei",
/* 26 */ C_0FUNC, 46 /* EdFindInFileList */, 0 , "find-in-filelist", "Sucht in mehreren Dateien;Suche in Files",
/* 27 */ C_1FUNC, 80 /* EdFindTag */, 0 , "find-tag", "Verzweigt zu einem Querverweis;Suche Verweis",
/* 28 */ C_0FUNC, 54 /* EdMarkSet */, 0 , "set-mark", "Setzt eine Textmarke;Setze Marke",
/* 29 */ C_0FUNC, 55 /* EdMarkGoto */, 0 , "goto-mark", "Geht zu einer Textmarke;Gehe zu Marke",
/* 30 */ C_0FUNC, 53 /* EdGotoLine */, 0 , "goto-line", "Geht zu einer Zeile;Gehe zu Zeile",
/* 31 */ C_1FUNC, 52 /* EdGotoLastPos */, TM_LASTSEARCH, "goto-last-pos", "Geht zur Position vor der letzten Suche;Letzte Position",
/* 32 */ C_0FUNC, 92 /* EdGotoPreviousTag */, 0 , "goto-previous-tag", "Geht zur Position vor der letzten Verzweigung;Letzte Verzweigung",
/* 33 */ C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_START, "mark-block-start", "Definiert den Start der Textblock-Markierung;Block Start",
/* 34 */ C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_END , "mark-block-end", "Definiert das Ende der Textblock-Markierung;Block Ende",
/* 35 */ C_1FUNC, 12 /* EdSyncSelectionWithCaret */, MARK_ALL , "mark-all", "Markiert den gesamten Text;Markiere Alles",
/* 36 */ C_0FUNC, 11 /* EdBlockHide */, 0 , "hide-block-marks", "Versteckt die Textblock-Markierung;Block Verstecken",
/* 37 */ C_0FUNC, 5 /* EdBlockFindStart */, 0 , "find-block-start", "Sucht den Anfang der Textblock-Markierung;Suche Block Start",
/* 38 */ C_0FUNC, 4 /* EdBlockFindEnd */, 0 , "find-block-end", "Sucht das Ende der Textblock-Markierung;Suche Block Ende",
/* 39 */ C_1FUNC, 9 /* EdBlockCut */, 0 , "yank-block", "Bringt den Textblock zur Ablage; Block -> Ablage",
/* 40 */ C_1FUNC, 9 /* EdBlockCut */, CUT_QUERYID, "yank-to-buffer", "Bringt den Block zu Buffer...;Block -> Buffer..",
/* 41 */ C_1FUNC, 9 /* EdBlockCut */, CUT_QUERYID|CUT_APPND, "append-block-to-buffer", "Hängt den Textblock an Buffer.. an;Block >> Buffer",
/* 42 */ C_1FUNC, 9 /* EdBlockCut */, CUT_APPND , "append-block-to-clipboard", "Hängt den Textblock an die Ablage an;Block >> Ablage",
/* 43 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_QUERYID, "paste-buffer", "Fügt Buffer... ein;Buffer einfügen",
/* 44 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_CLIP, "paste-clipboard", "Fügt den Inhalt der Ablage ein;Ablage -> Text",
/* 45 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_UNDO, "paste-trash", "Fügt den Inhalt des Papierkorbs ein;Papierkorb -> Text",
/* 46 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_XUNDO|PASTE_QUERYID, "paste-query-trash", "Fügt den Inhalt des ? - ten Papierkorb Speichers ein; Papierkorb # -> Text",
/* 47 */ C_1FUNC, 3 /* EdBlockDelete */, 1 , "delete-block", "Schneidet den markierten Textblock aus;Block Ausschneiden",
/* 48 */ C_0FUNC, 2 /* EdBlockCopy */, 0 , "copy-block", "Kopiert den markierten Textblock zum Cursor;Block Kopieren",
/* 49 */ C_0FUNC, 6 /* EdBlockMove */, 0 , "move-block", "Verschiebt den markierten Textblock zum Cursor;Block Verschieben",
/* 50 */ C_0FUNC, 13 /* EdLinesYank */, 0 , "yank-line", "Bringt die aktuelle Zeile zur Ablage;Zeile -> Ablage",
/* 51 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE|BLK_COLUMN_SELECTION, "toggle-column-selection", "Ändert die Form der Textauswahl;Auswahl in Spaltenform",
/* 52 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWCONTROL, "toggle-show-control", "Schaltet zum Controlzeichen-Anzeige-Modus;Zeige Control",
/* 53 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWRULER, "toggle-show-ruler", "Aktiviert die Tabulatorzeile; Zeige document descriptor",
/* 54 */ C_0FUNC, 114 /* EdPrinterLayout */, 0 , "dialog-printer-layout", "Stellt Optionen und Layout fürs Drucken ein;Drucken Layout",
/* 55 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWHEX, "toggle-alternate-status", "Verwendet die alternative Statuszeile;Alternativer Status",
/* 56 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE|SHOWATTR, "toggle-show-attributes", "Zeigt Text attributiert;Zeige Attribute",
/* 57 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_WMODE|WM_INSERT, "toggle-insert-mode", "Schaltet zwischen Einfügen und Überschreiben um;Einfügen / Überschreiben",
/* 58 */ C_0FUNC, 59 /* EdOptionSet */, 0 , "set-options", "Konfiguration des allgemeinen Betriebsmodus von PKS-EDIT;Einstellen",
/* 59 */ C_0FUNC, 18 /* EdFormatText */, 0 , "format-text", "Formatiert einen Textbereich;Format Text",
/* 60 */ C_1FUNC, 31 /* EdReplaceTabs */, 0 , "compress-tabs", "Faßt Leerzeichen zu Tabulatoren zusammen; Kompr. Tabs",
/* 61 */ C_1FUNC, 31 /* EdReplaceTabs */, 1 , "expand-tabs", "Epandiert Tabulatoren zu Leerzeichen; Exp. Tabs",
/* 62 */ C_0FUNC, 93 /* EdAlignText */, 0 , "align-text", "Richtet Textbereiche aus;Ausrichten Text",
/* 63 */ C_1FUNC, 87 /* EdRangeShift */, 1 , "shift-range-right", "Verschiebt einen Textbereich nach rechts;Schieben rechts",
/* 64 */ C_1FUNC, 87 /* EdRangeShift */, -1 , "shift-range-left", "Verschiebt einen Textbereich nach links;Schieben links",
/* 65 */ C_0FUNC, 69 /* EdSort */, 0 , "sort-text", "Sortiert einen Textbereich;Sortieren",
/* 66 */ C_1FUNC, 89 /* EdFilesCompare */, LIST_NEXT , "next-difference", "Geht zum nächsten Unterschied 2er Dateien;Vergleichen",
/* 67 */ C_1FUNC, 60 /* EdPrint */, PRT_CURRWI, "print-window", "Druckt das Bearbeitungsfenster;Drucken aktuelle Datei",
/* 68 */ C_1FUNC, 60 /* EdPrint */, PRT_CURRBLK, "print-block", "Druckt den markierten Textblock;Drucken Block",
/* 69 */ C_1FUNC, 60 /* EdPrint */, PRT_FILE , "print-file", "Druckt eine Datei;Drucken Datei",
/* 70 */ C_0FUNC, 66 /* EdCommandExecute */, 0 , "execute-command", "Startet eine externe Applikation;Programm Starten",
/* 71 */ C_0FUNC, 28 /* EdTagfileRead */, 0 , "read-tagfile", "Liest eine Verweisdatei;Lese Verweis",
/* 72 */ C_0FUNC, 21 /* EdSearchListRead */, 0 , "read-search-list", "Liest eine Suchliste;Lese Suchliste",
/* 73 */ C_1FUNC, 22 /* EdErrorListRead */, 0 , "read-compiler-errors", "Liest eine Compiler Fehler Liste;Lese Fehler",
/* 74 */ C_0FUNC, 26 /* EdDocMacrosAdd */, 0 , "add-doc-macros", "Fügt Dokumenteinstellungen (Abkürzungen, ...) einer Modusdatei hinzu;Erw. Modus",
/* 75 */ C_0FUNC, 45 /* EdMacroRecord */, 0 , "record-macro", "Startet/Stoppt eine Makro Aufnahme;Makro Aufnahme",
/* 76 */ C_0FUNC, 24 /* EdMacrosEdit */, 0 , "dialog-macros", "Editiert Makros und ihre Anbindungen;Makros bearbeiten",
/* 77 */ C_1FUNC, 27 /* macro_readWriteWithFileSelection */, 1 , "write-macros", "Schreibt eine Makrodatei;Schreiben Makros",
/* 78 */ C_1FUNC, 27 /* macro_readWriteWithFileSelection */, 0 , "read-macros", "Liest eine Makrodatei;Lesen Makros",
/* 79 */ C_0FUNC, 29 /* EdSetup */, 0 , "save-options", "Sichert alle Einstellungen;Sichern Desktop",
/* 80 */ C_0FUNC, 109 /* EdConfigureIcons */, 0 , "configure-icons", "Konfiguriert die Symbole des PKS-EDIT Desktops;Symbole bearb.",
/* 81 */ C_0FUNC, 75 /* EdDlgDispMode */, 0 , "dialog-display-mode", "Stellt den Anzeige-Modus ein;Modus Anzeige",
/* 82 */ C_0FUNC, 74 /* EdDlgWorkMode */, 0 , "dialog-work-mode", "Stellt den Bearbeitungs-Modus ein;Modus Beabeitung",
/* 83 */ C_0FUNC, 76 /* EdDlgCursTabs */, 0 , "dialog-text-cursor", "Stellt das Verhalten des Textcursors ein;Modus Cursor",
/* 84 */ C_0FUNC, 77 /* EdDlgModeVals */, 0 , "dialog-macro-bindings", "Stellt das Dateiformat ein;Format Datei",
/* 85 */ C_1FUNC, 23 /* doctypes_readWriteDocumentDescriptor */, 1 , "save-ruler", "Sichert die Dokument-Einstellungen;Sichern Dok.-Einst.",
/* 86 */ C_1FUNC, 23 /* doctypes_readWriteDocumentDescriptor */, 0 , "read-ruler", "Liest die Dokument-Einstellungen aus einer Datei;Lesen Dok.-Einst.",
/* 87 */ C_0FUNC, 71 /* EdInfoFiles */, 0 , "info-to-file", "Zeigt Informationen zu bearbeiteten Dateien;Fensterliste",
/* 88 */ C_1FUNC, 63 /* EdCloseAll */, 0 , "close-all-windows", "Schließt alle Bearbeitungs-Fenster;Alle schließen",
/* 89 */ C_1FUNC, 85 /* EdWinArrange */, WIN_ICONARRANGE, "arrange-icons", "Ordnet die Symbole auf dem Desktop an;Anordnen Symbole",
/* 90 */ C_1FUNC, 85 /* EdWinArrange */, WIN_CASCADE, "cascade-windows", "Legt alle Bearbeitungsfenster hintereinander;Gestapelt",
/* 91 */ C_1FUNC, 85 /* EdWinArrange */, WIN_TILE , "tile-windows", "Legt alle Bearbeitungsfenster nebeneinander;Fenster Neben.",
/* 92 */ C_1FUNC, 56 /* EdHelp */, HELP_HELPONHELP, "help-on-help", "Zeigt Anweisungen zum Gebrauch des Hilfesystems an;Gebrauch Hilfe",
/* 93 */ C_1FUNC, 110 /* EdHelpContext */, IDM_HLPONMENUS, "help-on-menus", "Zeigt Hilfen zu den PKS-EDIT Menus;Gebrauch Menüs",
/* 94 */ C_1FUNC, 110 /* EdHelpContext */, IDM_HLPONKEYS, "help-on-keys", "Zeigt Hilfen zu den Bearbeitungstasten von PKS-EDIT;Gebrauch Tasten",
/* 95 */ C_1FUNC, 110 /* EdHelpContext */, IDM_HLPONDESKTOP, "help-on-desktop", "Zeigt Hilfen zum Desktop von PKS-EDIT;Gebrauch Desktop",
/* 96 */ C_1FUNC, 56 /* EdHelp */, HELP_INDEX, "help-index", "Zeigt das Hilfen-Verzeichnis an;Hilfe Übersicht",
/* 97 */ C_0FUNC, 1 /* EdAbout */, 0 , "show-copyright", "Zeigt die Copyright-Meldung mit Serien- und Versionsnummer;Copyright",
/* 98 */ C_0FUNC, 16 /* EdKeycodeInsert */, 0 , "keycode-insert", "Fügt eine Tastenkombination als Text ein;Tastatur einf.",
/* 99 */ C_1FUNC, 86 /* EdWindowRegSet */, 0 , "set-win-reg-1", "Definiert Fenster-Register #0;Def. Fenster #0",
/* 100 */ C_1FUNC, 86 /* EdWindowRegSet */, 1 , "set-win-reg-2", "Definiert Fenster-Register #1;Def. Fenster #1",
/* 101 */ C_1FUNC, 86 /* EdWindowRegSet */, 2 , "set-win-reg-3", "Definiert Fenster-Register #2;Def. Fenster #2",
/* 102 */ C_1FUNC, 86 /* EdWindowRegSet */, 3 , "set-win-reg-4", "Definiert Fenster-Register #3;Def. Fenster #2",
/* 103 */ C_1FUNC, 86 /* EdWindowRegSet */, 4 , "set-win-reg-5", "Definiert Fenster-Register #4;Def. Fenster #3",
/* 104 */ C_1FUNC, 86 /* EdWindowRegSet */, 5 , "set-win-reg-6", "Definiert Fenster-Register #5;Def. Fenster #5",
/* 105 */ C_1FUNC, 85 /* EdWinArrange */, WIN_FULL , "set-win-zoomed", "Vergrößert das Bearbeitungsfenster auf maximale Größe;Vollbild",
/* 106 */ C_1FUNC, 85 /* EdWinArrange */, 0 , "size-win-with-reg-1", "Setzt Fenstergröße gemäß Fenster-Register #0;Größe Fenster #0",
/* 107 */ C_1FUNC, 85 /* EdWinArrange */, 1 , "size-win-with-reg-2", "Setzt Fenstergröße gemäß Fenster-Register #1;Größe Fenster #1",
/* 108 */ C_1FUNC, 85 /* EdWinArrange */, 2 , "size-win-with-reg-3", "Setzt Fenstergröße gemäß Fenster-Register #2;Größe Fenster #2",
/* 109 */ C_1FUNC, 85 /* EdWinArrange */, 3 , "size-win-with-reg-4", "Setzt Fenstergröße gemäß Fenster-Register #3;Größe Fenster #3",
/* 110 */ C_1FUNC, 85 /* EdWinArrange */, 4 , "size-win-with-reg-5", "Setzt Fenstergröße gemäß Fenster-Register #4;Größe Fenster #4",
/* 111 */ C_1FUNC, 85 /* EdWinArrange */, 5 , "size-win-with-reg-6", "Setzt Fenstergröße gemäß Fenster-Register #5;Größe Fenster #5",
/* 112 */ C_1FUNC, 65 /* EdSelectWindow */, 1 , "select-window-1", "Selektiert Fenster #1;Zu Fenster 1",
/* 113 */ C_1FUNC, 65 /* EdSelectWindow */, 2 , "select-window-2", "Selektiert Fenster #2;Zu Fenster 2",
/* 114 */ C_1FUNC, 65 /* EdSelectWindow */, 3 , "select-window-3", "Selektiert Fenster #3;Zu Fenster 3",
/* 115 */ C_1FUNC, 65 /* EdSelectWindow */, 4 , "select-window-4", "Selektiert Fenster #4;Zu Fenster 4",
/* 116 */ C_1FUNC, 65 /* EdSelectWindow */, 5 , "select-window-5", "Selektiert Fenster #5;Zu Fenster 5",
/* 117 */ C_1FUNC, 65 /* EdSelectWindow */, 6 , "select-window-6", "Selektiert Fenster #6;Zu Fenster 6",
/* 118 */ C_1FUNC, 65 /* EdSelectWindow */, -1 , "select-previous-window", "Aktiviert das zuletzt aktive Fenster;Vorh. Fenster",
/* 119 */ C_1FUNC, 65 /* EdSelectWindow */, SEL_CYCLE , "cycle-window", "Geht zyklisch zum nächsten Fenster;Weitersch. Fenster",
/* 120 */ C_0FUNC, 73 /* EdCharUpToLow */, 0 , "char-up-low", "wandelt Groß- in Kleinschreibung;Groß <-> Klein",
/* 121 */ C_1FUNC, 70 /* EdLinesShift */, -1 , "shift-line-left", "Verschiebt um eine Spalte nach links;Schieben links",
/* 122 */ C_1FUNC, 70 /* EdLinesShift */, 1 , "shift-line-right", "Verschiebt um eine Spalte nach rechts;Schieben rechts",
/* 123 */ C_0FUNC, 50 /* EdReplaceAgain */, 0 , "replace-again", "Wiederholt die letzte Ersetzung;Erneut ersetzen",
/* 124 */ C_1FUNC, 82 /* EdErrorNext */, LIST_NEXT , "errorlist-next", "Geht zum nächsten Compiler-Fehler;Suche Fehler",
/* 125 */ C_1FUNC, 82 /* EdErrorNext */, LIST_END , "errorlist-end", "Geht zum letzten Compiler-Fehler;Suche letzt. Fehler",
/* 126 */ C_1FUNC, 82 /* EdErrorNext */, LIST_PREV , "errorlist-previous", "Geht zum vorherigenen Compiler-Fehler;Suche Fehler <-",
/* 127 */ C_1FUNC, 82 /* EdErrorNext */, LIST_START, "errorlist-start", "Geht zum ersten Compiler-Fehler;Suche 1. Fehler",
/* 128 */ C_0FUNC, 72 /* EdShowMatch */, 0 , "check-brackets", "Überprüft Klammern - Paare;Prüfe {}",
/* 129 */ C_0FUNC, 51 /* EdCharControlInsert */, 0 , "insert-char-with-dialog", "Zeigt ein Formular mit dem aktuellen Zeichensatz;Einf. Sonderz.",
/* 130 */ C_1FUNC, 68 /* EdShiftBetweenBrackets */, -1 , "shift-between-brackets-left", "Verschiebt zwischen den Block zwischen Klammern nach links; Schieben {} links",
/* 131 */ C_1FUNC, 68 /* EdShiftBetweenBrackets */, 1 , "shift-between-brackets-right", "Verschiebt zwischen den Block zwischen Klammern nach rechts; Schieben {} rechts",
/* 132 */ C_1FUNC, 17 /* EdCharInsert */, 127 , "delete-char", "Löscht das Zeichen unter dem Cursor; Lösche Zeichen",
/* 133 */ C_1FUNC, 41 /* EdCharDelete */, MOT_TOEND , "delete-to-eol", "Löscht bis zum Ende der Zeile;Lösche zum Ende",
/* 134 */ C_1FUNC, 41 /* EdCharDelete */, MOT_SPACE, "delete-word", "Löscht das Wort unter dem Cursor;Lösche Wort",
/* 135 */ C_1FUNC, 41 /* EdCharDelete */, MOT_UNTILC, "delete-to-next-char", "Löscht bis zu Zeichen..;Lösche bis..",
/* 136 */ C_1FUNC, 41 /* EdCharDelete */, -MOT_SPACE, "delete-back-white", "Löscht bis zum letzten Leerzeichen;Lösche Wort2 <-",
/* 137 */ C_1FUNC, 41 /* EdCharDelete */, MOT_WORD, "delete-to-white", "Löscht bis zum nächsten Leerzeichen;Lösche Wort2",
/* 138 */ C_1FUNC, 41 /* EdCharDelete */, -MOT_TOEND, "delete-to-sol", "Löscht bis zum Anfang der Zeile;Lösche zum Anfang",
/* 139 */ C_1FUNC, 41 /* EdCharDelete */, -MOT_SPACE, "delete-back-word", "Löscht das Links vom Cursor stehende Wort;Lösche Wort <-",
/* 140 */ C_1FUNC, 41 /* EdCharDelete */, -MOT_UNTILC, "delete-until-previous-char", "Löscht bis zu Zeichen..;Lösche bis .. <-",
/* 141 */ C_1FUNC, 17 /* EdCharInsert */, 13 , "split-line", "Fügt ein Zeilenende ein;Zeilen Ende",
/* 142 */ C_1FUNC, 32 /* EdLineSplit */, RET_PLUS , "split-line-indent-plus", "Fügt ein Zeilenende ein mit Indent;Zeilen Ende+",
/* 143 */ C_1FUNC, 32 /* EdLineSplit */, RET_MINUS , "split-line-indent-minus", "Fügt ein Zeilenende ein mit Indent links;Zeilen Ende-",
/* 144 */ C_0FUNC, 57 /* EdLinesJoin */, 0 , "join-lines", "Vereiningt 2 Zeilen;Zeilen vereinig.",
/* 145 */ C_1FUNC, 39 /* EdCursorUp */, MOT_SINGLE, "cursor-up-line", "Bewegt den Cursor eine Zeile nach oben;Zeile hoch",
/* 146 */ C_1FUNC, 39 /* EdCursorUp */, MOT_TOEND , "cursor-top-of-page", "Bewegt den Cursor zum oberen Seitenende;Zeile Seite oben",
/* 147 */ C_1FUNC, 39 /* EdCursorUp */, MOT_WORD , "cursor-back-page", "Bewegt den Cursor eine Seite nach oben;Zeile Seite zurück",
/* 148 */ C_1FUNC, 40 /* EdCursorDown */, MOT_SINGLE, "cursor-down-line", "Bewegt den Cursor eine Zeile nach unten;Zeile runter",
/* 149 */ C_1FUNC, 40 /* EdCursorDown */, MOT_TOEND , "cursor-bottom-of-page", "Bewegt den Cursor zum unteren Seitenende;Zeile Seite unten",
/* 150 */ C_1FUNC, 40 /* EdCursorDown */, MOT_WORD , "cursor-down-page", "Bewegt den Cursor eine Seite nach unten;Zeile Seite nach unten",
/* 151 */ C_1FUNC, 37 /* EdCursorRight */, MOT_SINGLE, "cursor-right-char", "Bewegt den Cursor ein Zeichen nach rechts;Cursor rechts",
/* 152 */ C_1FUNC, 37 /* EdCursorRight */, MOT_TOEND , "cursor-eol", "Bewegt den Cursor zum Ende der Zeile;Cursor zum Ende",
/* 153 */ C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE, "cursor-right-word", "Bewegt den Cursor ein Wort nach rechts;Cursor Wort rechts",
/* 154 */ C_1FUNC, 37 /* EdCursorRight */, MOT_UNTILC, "cursor-until-char", "Bewegt den Cursor zum nächsten Zeichen ..;Cursor zu..",
/* 155 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_SINGLE, "cursor-left-char", "Bewegt den Cursor ein Zeichen nach links;Cursor links",
/* 156 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_TOEND , "cursor-sol", "Bewegt den Cursor zum Anfang der Zeile;Cursor Anfang",
/* 157 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE, "cursor-left-word", "Bewegt den Cursor ein Wort nach links;Cursor Wort <-",
/* 158 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_UNTILC, "cursor-back-to-char", "Bewegt den Cursor zum letzten Zeichen..;Cursor <- ..",
/* 159 */ C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE , "cursor-to-space", "Bewegt den Cursor zum nächsten Leerzeichen;Cursor zu Leer",
/* 160 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE , "cursor-back-to-space", "Bewegt den Cursor zum letzten Leerzeichen;Cursor letztes Leer.",
/* 161 */ C_1FUNC, 39 /* EdCursorUp */, MOT_FILE , "cursor-home", "Bewegt den Cursor zum Anfang der Datei;Zum Anfang",
/* 162 */ C_1FUNC, 40 /* EdCursorDown */, MOT_FILE , "cursor-eof", "Bewegt den Cursor zum Ende der Datei;Zum Ende",
/* 163 */ C_1FUNC, 19 /* EdLineInsert */, 0 , "insert-line-follow", "Fügt eine Zeile ein, Cursor folgt;Zeile einfügen",
/* 164 */ C_1FUNC, 14 /* EdLineDelete */, 0 , "delete-line-stay", "Löscht eine Zeile;Zeile löschen",
/* 165 */ C_1FUNC, 14 /* EdLineDelete */, CUT_APPND , "delete-line-append", "Hängt die aktuelle Zeile an den Papierkorb an;Zeile >> Papierkorb",
/* 166 */ C_1FUNC, 14 /* EdLineDelete */, 1 , "delete-line-follow", "Löscht die Zeile, Cursor folgt;Zeile löschen |",
/* 167 */ C_1FUNC, 0 /* EdFileAbandon */, 0 , "abandon-file", "Liest die aktuelle Datei neu;Neu lesen",
/* 168 */ C_1FUNC, 64 /* EdSaveFile */, SAV_SAVE|SAV_QUIT, "save-and-close", "Sichert und schließt das Bearbeitungsfenster;Sichern & Schließen",
/* 169 */ C_1FUNC, 19 /* EdLineInsert */, 1 , "insert-line-stay", "Fügt eine Zeile ein, Cursor bleibt;Zeile einfügen",
/* 170 */ C_0FUNC, 25 /* EdDocMacrosEdit */, 0 , "edit-doc-macros", "Editiert weitere Dokumenteinstellungen;Edit erw. Dok",
/* 171 */ C_0FUNC, 15 /* EdBufferFree */, 0 , "kill-buffers", "Leert alle Text-Zwischenspeicher;Buffer leeren",
/* 172 */ C_1FUNC, 20 /* EdMarkedLineOp */, MLN_DELETE, "delete-marked-lines", "Löscht alle markierten Zeilen;Lösche Liste",
/* 173 */ C_0FUNC, 30 /* EdSetMultiplier */, 0 , "set-multiplikator", "Setzt den Multiplikator für die nächste Funktion;Multiplikator",
/* 174 */ C_0FUNC, 43 /* EdMacroEscape */, 0 , "escape-makro", "Startet ein Escape Makro;Tasten Makro",
/* 175 */ C_1FUNC, 42 /* fkey_keyModifierStateChanged */, -1 , "switch-fkeys-minus", "Schaltet die Funktionstasten zurück;Funktions Tasten <-",
/* 176 */ C_0FUNC, 113 /* EdDocTypes */, 0 , "dialog-doc-types", "Definiert Dokument Typen;Def. Dok. Typen",
/* 177 */ C_1FUNC, 42 /* fkey_keyModifierStateChanged */, 1 , "switch-fkeys-plus", "Schaltet die Funktionstasten weiter;Funktionstasten ->",
/* 178 */ C_1FUNC, 44 /* macro_executeMacroByIndex */, MAC_AUTO , "re-insert", "Wiederholt die letzten Einfüge-Operationen;Wieder einfügen",
/* 179 */ C_0FUNC, 45 /* EdMacroRecord */, 0 , "record-macro", "Startet eine Makro-Aufnahme;Makro aufnehmen",
/* 180 */ C_0FUNC, 88 /* EdUndo */, 0 , "undo", "Macht die letzte Änderung rückgängig;Änderung rückgängig",
/* 181 */ C_1FUNC, 20 /* EdMarkedLineOp */, MLN_TOGGLE, "toggle-line-marks", "Invertiert die Zeilenmarkierungen;Invert. mark. Zeilen",
/* 182 */ C_1FUNC, 85 /* EdWinArrange */, WIN_DESKICON, "iconize-edit", "Iconisiert PKS-EDIT;PKS-EDIT als Symbol",
/* 183 */ C_1FUNC, 85 /* EdWinArrange */, WIN_ICONIZED, "iconize-window", "Iconisiert das Bearbeitungsfenster;Fenster als Symbol",
/* 184 */ C_1FUNC, 89 /* EdFilesCompare */, LIST_PREV , "last-difference", "Geht zum letzten Unterschied beim Datei - Vergleich;Letzter Unterschied",
/* 185 */ C_1FUNC, 90 /* EdScrollScreen */, MOT_SINGLE, "scroll-up-line", "Scrollt eine Zeile nach oben, Cursor bleibt;Rollen hoch 1",
/* 186 */ C_1FUNC, 90 /* EdScrollScreen */, -MOT_SINGLE, "scroll-down-line", "Scrollt eine Zeile nach unten, Cursor bleibt;Rollen runter 1",
/* 187 */ C_1FUNC, 90 /* EdScrollScreen */, MOT_PAGE , "scroll-up-page", "Scrollt eine Seite nach oben, Cursor bleibt;Rollen Seite 1",
/* 188 */ C_1FUNC, 90 /* EdScrollScreen */, -MOT_PAGE , "scroll-down-page", "Scrollt eine Seite nach unten, Cursor bleibt;Rollen Seite u. 1",
/* 189 */ C_1FUNC, 40 /* EdCursorDown */, MOT_CENTER, "cursor-center-page", "Bewegt den Cursor zur Seitenmitte;Zur Seitenmitte",
/* 190 */ C_1FUNC, 91 /* EdScrollCursor */, MOT_SINGLE, "scroll2-up-line", "Scrollt eine Zeile nach oben, Cursor folgt;Rollen oben 2",
/* 191 */ C_1FUNC, 91 /* EdScrollCursor */, -MOT_SINGLE, "scroll2-down-line", "Scrollt eine Zeile nach unten, Cursor folgt;Rollen unten 2",
/* 192 */ C_1FUNC, 91 /* EdScrollCursor */, MOT_CENTER, "scroll-center-page", "Scrollt den Bildschirm so, daß der Cursor in der Mitte steht;Rollen mittig",
/* 193 */ C_1FUNC, 20 /* EdMarkedLineOp */, MLN_JOIN , "join-marked-lines", "Fügt alle markierten Zeilen zusammen;Join Zeilen",
/* 194 */ C_0FUNC, 25 /* EdDocMacrosEdit */, 0 , "edit-local-doc-macros", "Dokumenteinstellungen;Edit erw. Dok",
/* 195 */ C_1FUNC, 52 /* EdGotoLastPos */, TM_LASTINSERT, "goto-last-insert-pos", "Geht zur Stelle der letzten Einfügung;Zur letzten Einfügung",
/* 196 */ C_1FUNC, 60 /* EdPrint */, PRT_CLIP , "print-clipboard", "Druckt den Inhalt der Zwischenablage;Drucken Ablage",
/* 197 */ C_1FUNC, 60 /* EdPrint */, PRT_TRASH , "print-trash", "Druckt den Inhalt des Papierkorbs;Drucken Papierkorb",
/* 198 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_ICON|PASTE_UNDO, "paste-undo", "Fügt den Papierkorb von einem Icon ein",
/* 199 */ C_1FUNC, 10 /* EdBlockPaste */, PASTE_ICON|PASTE_CLIP, "paste-clip-icon", "Fügt die Ablage von einem Icon ein",
/* 200 */ C_0FUNC, 67 /* EdExecute */, 0 , "icon-execute", "Führt ein an ein Symbol gebundenes Kommando aus",
/* 201 */ C_0FUNC, 94 /* ic_closeIconWindow */, 0 , "remove-icon", "Löscht ein Symbol",
/* 202 */ C_1FUNC, 99 /* EdMousePositionUngrabbed */, 1 , "cursor-mouse-goto", "Positioniert den Cursor mit der Maus",
/* 203 */ C_1FUNC, 97 /* EdMouseMoveText */, 0 , "drag-copy-text", "Kopiert Text mit der Maus",
/* 204 */ C_1FUNC, 97 /* EdMouseMoveText */, 1 , "drag-move-text", "Bewegt Text mit der Maus",
/* 205 */ C_1FUNC, 98 /* EdMouseSelectLines */, 1 , "mouse-select-lines", "Markiert einzelne Zeilen",
/* 206 */ C_1FUNC, 98 /* EdMouseSelectLines */, 0 , "mouse-unselect-lines", "Entfernt einzelne Zeilen - Markierungen",
/* 207 */ C_1FUNC, 44 /* macro_executeMacroByIndex */, MAC_LASTREC, "play-last-macro", "Spielt das letzte aufgenmommene Makro ab",
/* 208 */ C_1FUNC, 95 /* EdBlockMouseMark */, 0 , "mouse-mark-block", "Markiert eine Textblock mit der Maus",
/* 209 */ C_1FUNC, 96 /* EdMouseMarkParts */, MOT_TOEND , "mouse-mark-line", "Markiert die aktuelle Zeile mit der Maus / konventioneller Modus",
/* 210 */ C_1FUNC, 96 /* EdMouseMarkParts */, MOT_WORD , "mouse-mark-word", "Markiert das aktuelle Wort mit der Maus",
/* 211 */ C_1FUNC, 96 /* EdMouseMarkParts */, MOT_SPACE , "mouse-mark-to-space", "Markiert bis zum nächsten Leerzeichen mit der Maus",
/* 212 */ C_1FUNC, 96 /* EdMouseMarkParts */, MOT_PGRPH , "mouse-mark-paragraph", "Markiert den aktuellen Absatz mit der Maus",
/* 213 */ C_1FUNC, 95 /* EdBlockMouseMark */, 0, "mouse-update-block", "Markiert mit der Maus - Erweiterungs Modus",
/* 214 */ C_1FUNC, 111 /* EdListBindings */, LIST_MACROS, "macro-list", "listet alle Makros;Makros listen",
/* 215 */ C_1FUNC, 111 /* EdListBindings */, LIST_KEYS , "key-list", "Listet alle Tastenbelegungen;Tasten listen",
/* 216 */ C_1FUNC, 111 /* EdListBindings */, LIST_MICE , "mouse-list", "Listet alle Maustasten - Funktionen;Maustasten listen",
/* 217 */ C_1FUNC, 112 /* EdCompileMacros */, 1 , "compile-macros", "Makros im aktuellen Fenster compilieren...;Makros compilieren",
/* 218 */ C_1FUNC, 17 /* EdCharInsert */, 10 , "split-line-soft", "Fügt ein weiches Zeilenende ein;Weiches Zeilenende",
/* 219 */ C_1FUNC, 117 /* EdShowClipboard */, 0 , "show-std-clip", "Ruft CLIPBRD.EXE zur Anzeige der Standard - Ablage;Zeigen Ablage",
/* 220 */ C_1FUNC, 3 /* EdBlockDelete */, 0 , "erase-block", "Löscht den markierten Textblock;Block Löschen",
/* 221 */ C_1FUNC, 111 /* EdListBindings */, LIST_MENUS, "menu-list", "Listet das aktuelle Menu in PKS-MakroC Format;Listen Menü",
/* 222 */ C_0FUNC, 120 /* EdRedo */, 0, "redo", "Wiederholt das Kommando vor dem letzten Undo;Letztes Kommando wiederholen",
/* 223 */ C_1FUNC, 78 /* EdOptionToggle */, OPT_DMODE | SHOWLINENUMBERS, "toggle-show-linenumbers", "Zeigt Zeilennummern an; Zeilennummern anzeigen",
/* 224 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_SINGLE|MOT_XTNDBLOCK, "select-left", "Wählt ein Zeichen weiter links aus;Auswahl links",
/* 225 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_TOEND | MOT_XTNDBLOCK, "select-left-to-start", "Wählt bis Anfang der Zeile aus;Auswahl Anfang",
/* 226 */ C_1FUNC, 38 /* EdCursorLeft */, MOT_SPACE | MOT_XTNDBLOCK, "select-left-word", "Selektiert das Wort links vom Cursor;Auswahl Wort links",
/* 227 */ C_1FUNC, 37 /* EdCursorRight */, MOT_SINGLE | MOT_XTNDBLOCK, "select-right", "Wählt das nächste Zeichen aus;Auswahl rechts",
/* 228 */ C_1FUNC, 37 /* EdCursorRight */, MOT_SPACE | MOT_XTNDBLOCK, "select-right-word", "Wählt das Wort zum nächsten Zeichen aus;Auswahl Wort rechts",
/* 229 */ C_1FUNC, 37 /* EdCursorRight */, MOT_TOEND | MOT_XTNDBLOCK, "select-right-to-end", "Wählt zum Ende der Zeile aus;Auswahl Zeile rechts",
/* 230 */ C_1FUNC, 39 /* EdCursorUp */, MOT_SINGLE | MOT_XTNDBLOCK, "select-up", "Wählt eine Zeile weiter nach open aus;Auswahl oben",
/* 231 */ C_1FUNC, 40 /* EdCursorDown */, MOT_SINGLE | MOT_XTNDBLOCK, "select-down", "Wählt eine Zeile weiter nach unten aus;Auswahl unten",
/* 232 */ C_1FUNC, 39 /* EdCursorUp */, MOT_PAGE | MOT_XTNDBLOCK, "select-page-up", "Wählt eine Seite weiter nach open aus;Auswahl Seite hoch",
/* 233 */ C_1FUNC, 40 /* EdCursorDown */, MOT_PAGE | MOT_XTNDBLOCK, "select-page-down", "Wählt eine Seite weiter nach unten aus;Auswahl Seite runter",
/* 234 */ C_1FUNC, 121 /* EdSaveAllFiles*/, 0, "save-all-files", "Speichert alle ungeänderten Dateien;Alle Dateien speichern",
/* 235 */ C_1FUNC, 114 /* find_initiateIncrementalSearch */, 0, "search-incrementally", "Inkrementelle Suche starten;Inkrementelle Suche starten",
/* 236 */ C_1FUNC, 122 /* ft_cloneWindow */, 0, "clone-window", "Zusätzliches Fenster öffnen;Zusätzliches Fenster",
};

char _recorder[RECORDERSPACE];
int _lcomseq = 1332;
int _ncmdseq = sizeof(_cmdseqtab)/sizeof(_cmdseqtab[0]);

KEYBIND _keymaptab[MAXMAPKEY] = {
0x445 , CMD_CMDSEQ, 0 /* comm-seq */,
0x451 , CMD_CMDSEQ, 9 /* comm-seq */,
0x857 , CMD_CMDSEQ, 11 /* comm-seq */,
0x457 , CMD_CMDSEQ, 12 /* comm-seq */,
0x842 , CMD_CMDSEQ, 13 /* comm-seq */,
0x854 , CMD_CMDSEQ, 14 /* comm-seq */,
0x45a , CMD_CMDSEQ, 15 /* comm-seq */,
0x85a , CMD_CMDSEQ, 16 /* comm-seq */,
0x446 , CMD_CMDSEQ, 17 /* comm-seq */,
0x452 , CMD_CMDSEQ, 18 /* comm-seq */,
0x460 , CMD_CMDSEQ, 19 /* comm-seq */,
0x441 , CMD_CMDSEQ, 20 /* comm-seq */,
0x442 , CMD_CMDSEQ, 21 /* comm-seq */,
0x75  , CMD_CMDSEQ, 22 /* comm-seq */,
0x76  , CMD_CMDSEQ, 23 /* comm-seq */,
0x475 , CMD_CMDSEQ, 24 /* comm-seq */,
0x476 , CMD_CMDSEQ, 25 /* comm-seq */,
0x455 , CMD_CMDSEQ, 26 /* comm-seq */,
0x449 , CMD_CMDSEQ, 27 /* comm-seq */,
0x44d , CMD_CMDSEQ, 28 /* comm-seq */,
0x4dd , CMD_CMDSEQ, 29 /* comm-seq */,
0x447 , CMD_CMDSEQ, 30 /* comm-seq */,
0x4be , CMD_CMDSEQ, 31 /* comm-seq */,
0x71  , CMD_CMDSEQ, 33 /* comm-seq */,
0x72  , CMD_CMDSEQ, 34 /* comm-seq */,
0xc70 , CMD_CMDSEQ, 35 /* comm-seq */,
0x871 , CMD_CMDSEQ, 36 /* comm-seq */,
0x471 , CMD_CMDSEQ, 37 /* comm-seq */,
0x472 , CMD_CMDSEQ, 38 /* comm-seq */,
0x73  , CMD_CMDSEQ, 39 /* comm-seq */,
0x473 , CMD_CMDSEQ, 40 /* comm-seq */,
0x372 , CMD_CMDSEQ, 41 /* comm-seq */,
0x373 , CMD_CMDSEQ, 42 /* comm-seq */,
0x474 , CMD_CMDSEQ, 43 /* comm-seq */,
0x74  , CMD_CMDSEQ, 44 /* comm-seq */,
0x32d , CMD_CMDSEQ, 45 /* comm-seq */,
0x7a  , CMD_CMDSEQ, 46 /* comm-seq */,
0x873 , CMD_CMDSEQ, 47 /* comm-seq */,
0x874 , CMD_CMDSEQ, 48 /* comm-seq */,
0x872 , CMD_CMDSEQ, 49 /* comm-seq */,
0x459 , CMD_CMDSEQ, 50 /* comm-seq */,
0x853 , CMD_CMDSEQ, 51 /* comm-seq */,
0x8be , CMD_CMDSEQ, 52 /* comm-seq */,
0x44c , CMD_CMDSEQ, 53 /* comm-seq */,
0x2d  , CMD_CMDSEQ, 57 /* comm-seq */,
0x86a , CMD_CMDSEQ, 58 /* comm-seq */,
0x84e , CMD_CMDSEQ, 66 /* comm-seq */,
0x844 , CMD_CMDSEQ, 67 /* comm-seq */,
0x858 , CMD_CMDSEQ, 70 /* comm-seq */,
0x90  , CMD_CMDSEQ, 75 /* comm-seq */,
0x42f , CMD_CMDSEQ, 76 /* comm-seq */,
0x849 , CMD_CMDSEQ, 98 /* comm-seq */,
0x731 , CMD_CMDSEQ, 99 /* comm-seq */,
0x732 , CMD_CMDSEQ, 100 /* comm-seq */,
0x733 , CMD_CMDSEQ, 101 /* comm-seq */,
0x734 , CMD_CMDSEQ, 102 /* comm-seq */,
0x735 , CMD_CMDSEQ, 103 /* comm-seq */,
0x736 , CMD_CMDSEQ, 104 /* comm-seq */,
0x430 , CMD_CMDSEQ, 105 /* comm-seq */,
0x831 , CMD_CMDSEQ, 106 /* comm-seq */,
0x832 , CMD_CMDSEQ, 107 /* comm-seq */,
0x833 , CMD_CMDSEQ, 108 /* comm-seq */,
0x834 , CMD_CMDSEQ, 109 /* comm-seq */,
0x835 , CMD_CMDSEQ, 110 /* comm-seq */,
0x836 , CMD_CMDSEQ, 111 /* comm-seq */,
0x431 , CMD_CMDSEQ, 112 /* comm-seq */,
0x432 , CMD_CMDSEQ, 113 /* comm-seq */,
0x433 , CMD_CMDSEQ, 114 /* comm-seq */,
0x434 , CMD_CMDSEQ, 115 /* comm-seq */,
0x435 , CMD_CMDSEQ, 116 /* comm-seq */,
0x436 , CMD_CMDSEQ, 117 /* comm-seq */,
0x4bf , CMD_CMDSEQ, 118 /* comm-seq */,
0xf2a , CMD_CMDSEQ, 119 /* comm-seq */,
0x87b , CMD_CMDSEQ, 120 /* comm-seq */,
0x409 , CMD_CMDSEQ, 121 /* comm-seq */,
0x309 , CMD_CMDSEQ, 122 /* comm-seq */,
0x454 , CMD_CMDSEQ, 123 /* comm-seq */,
0x44e , CMD_CMDSEQ, 124 /* comm-seq */,
0xc4e , CMD_CMDSEQ, 125 /* comm-seq */,
0x450 , CMD_CMDSEQ, 126 /* comm-seq */,
0xc50 , CMD_CMDSEQ, 127 /* comm-seq */,
0x4bb , CMD_CMDSEQ, 128 /* comm-seq */,
0x42d , CMD_CMDSEQ, 129 /* comm-seq */,
0x6d  , CMD_CMDSEQ, 130 /* comm-seq */,
0x6b  , CMD_CMDSEQ, 131 /* comm-seq */,
0x2e  , CMD_CMDSEQ, 132 /* comm-seq */,
0x32e , CMD_CMDSEQ, 133 /* comm-seq */,
0x42e , CMD_CMDSEQ, 134 /* comm-seq */,
0x82e , CMD_CMDSEQ, 135 /* comm-seq */,
0xc08 , CMD_CMDSEQ, 136 /* comm-seq */,
0xc2e , CMD_CMDSEQ, 137 /* comm-seq */,
0x308 , CMD_CMDSEQ, 138 /* comm-seq */,
0x408 , CMD_CMDSEQ, 139 /* comm-seq */,
0x808 , CMD_CMDSEQ, 140 /* comm-seq */,
0xd   , CMD_CMDSEQ, 141 /* comm-seq */,
0x80d , CMD_CMDSEQ, 142 /* comm-seq */,
0x40d , CMD_CMDSEQ, 143 /* comm-seq */,
0x30d , CMD_CMDSEQ, 144 /* comm-seq */,
0x26  , CMD_CMDSEQ, 145 /* comm-seq */,
0x326 , CMD_CMDSEQ, 146 /* comm-seq */,
0x426 , CMD_CMDSEQ, 147 /* comm-seq */,
0x28  , CMD_CMDSEQ, 148 /* comm-seq */,
0x328 , CMD_CMDSEQ, 149 /* comm-seq */,
0x428 , CMD_CMDSEQ, 150 /* comm-seq */,
0x27  , CMD_CMDSEQ, 151 /* comm-seq */,
0x327 , CMD_CMDSEQ, 152 /* comm-seq */,
0x427 , CMD_CMDSEQ, 153 /* comm-seq */,
0x846 , CMD_CMDSEQ, 154 /* comm-seq */,
0x25  , CMD_CMDSEQ, 155 /* comm-seq */,
0x325 , CMD_CMDSEQ, 156 /* comm-seq */,
0x425 , CMD_CMDSEQ, 157 /* comm-seq */,
0xb46 , CMD_CMDSEQ, 158 /* comm-seq */,
0xc25 , CMD_CMDSEQ, 159 /* comm-seq */,
0xc27 , CMD_CMDSEQ, 160 /* comm-seq */,
0x24  , CMD_CMDSEQ, 161 /* comm-seq */,
0x23  , CMD_CMDSEQ, 162 /* comm-seq */,
0x70  , CMD_CMDSEQ, 163 /* comm-seq */,
0x77  , CMD_CMDSEQ, 164 /* comm-seq */,
0x877 , CMD_CMDSEQ, 165 /* comm-seq */,
0x477 , CMD_CMDSEQ, 166 /* comm-seq */,
0x378 , CMD_CMDSEQ, 167 /* comm-seq */,
0x478 , CMD_CMDSEQ, 168 /* comm-seq */,
0x470 , CMD_CMDSEQ, 169 /* comm-seq */,
0x870 , CMD_CMDSEQ, 170 /* comm-seq */,
0x377 , CMD_CMDSEQ, 171 /* comm-seq */,
0x371 , CMD_CMDSEQ, 172 /* comm-seq */,
0x81b , CMD_CMDSEQ, 173 /* comm-seq */,
0x1b  , CMD_CMDSEQ, 174 /* comm-seq */,
0x403 , CMD_CMDSEQ, 175 /* comm-seq */,
0x91  , CMD_CMDSEQ, 177 /* comm-seq */,
0x420 , CMD_CMDSEQ, 178 /* comm-seq */,
0x47b , CMD_CMDSEQ, 75 /* comm-seq */,
0x854,	CMD_CMDSEQ, 222 /* comm-seq */,
0x855 , CMD_CMDSEQ, 180 /* comm-seq */,
0xb71 , CMD_CMDSEQ, 181 /* comm-seq */,
0x437 , CMD_CMDSEQ, 182 /* comm-seq */,
0x837 , CMD_CMDSEQ, 183 /* comm-seq */,
0x850 , CMD_CMDSEQ, 184 /* comm-seq */,
0x84a , CMD_CMDSEQ, 185 /* comm-seq */,
0x84b , CMD_CMDSEQ, 186 /* comm-seq */,
0x74a , CMD_CMDSEQ, 187 /* comm-seq */,
0x74b , CMD_CMDSEQ, 188 /* comm-seq */,
0xb4a , CMD_CMDSEQ, 189 /* comm-seq */,
0xc26 , CMD_CMDSEQ, 190 /* comm-seq */,
0xc28 , CMD_CMDSEQ, 191 /* comm-seq */,
0xb4b , CMD_CMDSEQ, 192 /* comm-seq */,
0x878 , CMD_CMDSEQ, 193 /* comm-seq */,
0x870 , CMD_CMDSEQ, 194 /* comm-seq */,
0x7be , CMD_CMDSEQ, 195 /* comm-seq */,
0x79  , CMD_CMDSEQ, 217 /* comm-seq */,
0x84a , CMD_CMDSEQ, 218 /* comm-seq */,
0x873 , CMD_CMDSEQ, 220 /* comm-seq */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */,
0x0   , 0       , 220 /* unused */};

