//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch en-US.rc
//
#define IDS_DELUNTILC                   0
#define IDS_MARKGOTO                    1
#define IDS_MARKSET                     2
#define IDS_MACROESCAPE                 3
#define IDBUT3                          3
#define IDS_GETBLOCK                    4
#define IDD_ALL_OCCURRENCES             4
#define IDS_COMPRESSTABS                7
#define IDS_EXPANDTABS                  8
#define IDS_SHIFTLEFT                   9
#define IDS_SHIFTRIGHT                  10
#define IDS_CURSUNTILC                  11
#define IDS_QUERYDELETE                 12
#define IDS_QUERYMKDIR                  13
#define MCLONEWINDOW                    13
#define IDS_RENAME                      14
#define IDS_RNGONCE                     16
#define IDS_RNGLINE                     17
#define IDS_RNGCHAPTER                  18
#define IDS_RNGBLOCK                    19
#define IDS_RNGTOCURS                   20
#define IDS_RNGFROMCURS                 21
#define IDS_RNGGLOBAL                   22
#define MOPENF                          23
#define MQUITF                          25
#define MSAVEF                          27
#define MSAVERES                        28
#define MSAVEAS                         29
#define MSAVEALL_NO_EXIT                30
#define MREADF                          31
#define IDS_ABRTRETREIVE                32
#define MWRITEF                         32
#define IDS_ABRTREPLACE                 33
#define MABANDON                        33
#define IDS_ABRTSORT                    34
#define IDS_ABRTALIGN                   35
#define MSAVEALL                        35
#define IDS_ABRTMACRO                   36
#define MEXIT                           36
#define IDS_ABRTCONVERT                 37
#define IDS_ABRTFORMAT                  38
#define MFIND                           38
#define IDS_ABRTPRINT                   39
#define MREPLACE                        39
#define IDS_ABRTCMDCOMPLETE             40
#define MFAGAIN                         40
#define MEDIFLIS                        42
#define MSHOWTAG                        43
#define MSETMARK                        45
#define MGOTOMAR                        46
#define IDS_PRTERR                      48
#define MGOTOLN                         48
#define IDS_PRTERRABRT                  49
#define IDS_PRTERRUSRABRT               50
#define MLASTPOS                        50
#define IDS_PRTERRNOSPCE                51
#define MFLASTP                         51
#define IDS_PRTERRNOMEM                 52
#define MTMSTART                        54
#define MTMEND                          55
#define MTMHIDE                         56
#define MTMFSTAR                        57
#define MTMFEND                         58
#define MTCUT                           60
#define MTPASTE                         61
#define MTDEL                           62
#define MTCOPY                          63
#define IDS_MSGNREPL                    64
#define MTMOVE                          64
#define IDS_MSGNFOUND                   65
#define IDS_MSGNEWFILE                  66
#define IDS_MSGSAVEFILE                 67
#define IDS_MSGCUTBLOCK                 68
#define MFORMAT                         68
#define IDS_MSGEXPANDTABS               69
#define MCOMTABS                        69
#define IDS_MSGWIREGDEF                 70
#define MEXPTABS                        70
#define IDS_MSGAUBE                     71
#define MENALIGN                        71
#define IDS_MSGINWORK                   72
#define MSHFTRIG                        72
#define IDS_MSGDELICON                  73
#define MSHFTLEF                        73
#define IDS_MSGNOTIMER                  74
#define MMSORT                          74
#define IDS_MSGNOPRINTER                75
#define IDS_MSGOVERWRITE                76
#define IDS_MSGQUERYNEWFILE             77
#define IDS_MSGABANDON                  78
#define IDS_MSGNOBRACKETS               79
#define IDS_MSGUNDEFWINREG              80
#define IDS_MSGNOLASTPOS                81
#define IDS_MSGOLDMACS                  82
#define MEXEC                           82
#define IDS_MSGBADMACFORMAT             83
#define IDS_MSGSAVESEQ                  84
#define MREADTAG                        84
#define IDS_MSGMACDOUBLEDEF             85
#define MREAD_SEARCH_LIST               85
#define IDS_MSGQUITORSAVE               86
#define MREADCMP                        86
#define IDS_MSGWRONGWINDOW              87
#define MADDDOCMAC                      87
#define IDS_MSGLINETOOLONG              88
#define MMRECORDER                      88
#define IDS_MSGNOSPCE                   89
#define MMACEDIT                        89
#define IDS_MSGABRT                     90
#define MREADSEQ                        90
#define MWRSEQ                          91
#define IDS_MSGEXECERR                  92
#define IDS_MSGTOOMANYMACROS            93
#define MOPTION                         93
#define IDS_MSGMACFORMATERR             94
#define IDS_MSGBADICONACTION            95
#define IDS_MSGRDONLY                   96
#define IDS_MSGUNKNOWNMAC               97
#define IDS_MSGMACOVERFLOW              98
#define MEDITDOCMAC                     98
#define IDS_MSGMACRORECURSION           99
#define IDS_MSGPOSITIONMOUSECURS        100
#define IDS_MSGEXECERROR                101
#define IDS_MSGMARKUNDEF                102
#define IDS_MSGNOREPLACESTRING          103
#define MMSHOWCO                        103
#define IDS_MSGNOSEARCHSTRING           104
#define MMSHOWLI                        104
#define IDD_LOWOPT3                     104
#define IDS_MSGTOOMUCHFIELDS            105
#define IDS_MSGTOOMUCHSORTKEYS          106
#define IDM_HEX_DISPLAY                 106
#define IDS_MSGINVALSORTOPT             107
#define MMSHOWAT                        107
#define IDS_MSGTOOMUCHRECORDS           108
#define MMSHOWLINENUMBERS               108
#define IDM_LINE_SELECTION              109
#define IDS_MSGNOTRASH                  109
#define IDM_COLUMN_SELECTION            110
#define IDS_MSGNOUNDO                   110
#define IDS_MSGNOCLIP                   111
#define IDS_MSGNOBLOCKSELECTED          112
#define IDS_MSGBADBLOCKMOVE             113
#define IDS_MSGWPROTECT                 114
#define IDM_CLOSEALL                    114
#define IDS_MSGERRCHMOD                 115
#define IDS_MSGNOMOREDIFFS              116
#define IDM_ABOUT                       116
#define IDS_MSGDIFFTWOWINDOWS           117
#define IDD_OPT18                       117
#define IDS_MSGCLIPNOTCOMPLETE          118
#define IDS_MSGESCAPEUNDEF              119
#define IDS_MSGMACROIDTOOLONG           120
#define IDM_DISPMODE                    120
#define IDS_MSGMISSINGAPOSTRPOHE        121
#define IDM_WORKMODE                    121
#define IDS_MSGTOOMANYCOMPILERS         122
#define IDM_CURSTABS                    122
#define IDS_MSGWRONGKEYDEF              123
#define IDM_MODEVALS                    123
#define IDS_MSGTOOMANYRULERS            124
#define IDM_INFOFILE                    124
#define IDS_MSGGLOBALDEF                125
#define IDS_MSGWRONGTAGFORMAT           126
#define IDS_MSGUNKNWONTAG               127
#define IDM_PRINTTEXT                   127
#define IDS_MSGNOTAGFILE                128
#define IDS_MSGUNKNOWNCOMPILER          129
#define IDM_PRINTFILE                   129
#define IDS_MSGNOMOREERRS               130
#define IDM_COMPILEMACROS               130
#define IDS_MSGSTRINGNOTFOUND           131
#define IDM_MACROLIST                   131
#define IDS_MSGFILENOTFOUND             132
#define IDM_KEYLIST                     132
#define IDS_MSGWRAPPED                  133
#define IDM_MOUSELIST                   133
#define IDS_MSGNOMATCHTOEND             134
#define IDM_MENULIST                    134
#define IDS_MSGNOMATCHTOSTART           135
#define IDS_MSGNORANGESELECTED          136
#define IDS_MSGREADERROR                137
#define IDS_MSGWRAPPEDLINES             138
#define IDS_MSGNODISKSPACE              139
#define IDS_MSGCLEARBUFFERS             140
#define IDS_MSGNOUNDOBLOCK              141
#define IDS_MSGOPEN                     142
#define IDS_MSGNOHELP                   143
#define IDS_MSGWRITEERR                 144
#define IDS_MSGDELOLDKEYBIND            145
#define IDS_MSGFILESHAVECHANGED         146
#define IDS_STRING148                   148
#define IDM_HLPINDEX                    150
#define IDM_HLPONDESKTOP                151
#define IDM_HLPONMENUS                  152
#define IDM_HLPONKEYS                   153
#define IDM_HLPONHLP                    154
#define DLG_SAVEAS_OPTIONS              156
#define IDS_MSGRENOTNULL                160
#define IDM_DOCTYPES                    160
#define IDS_MSGRECOMPLEXEXPR            161
#define IDS_MSGREMACRORANGESYNTAX       162
#define IDS_MSGRERANGE                  163
#define IDS_MSGREMANYBRACKETS           164
#define IDS_MSGRENOBRACKETMATCH         165
#define IDS_MSGREFROMTO                 166
#define IDS_MSGREMINMAXOVL              167
#define IDS_MSGREMINMAXERR              168
#define IDS_MSGREBSLERR                 169
#define IDS_MSGREBRUNDEF                170
#define IDS_MSGREPIPEERR                171
#define IDS_MSGWRONGPW                  172
#define IDS_MSGDIFFERENTPW              173
#define IDS_MSGINVALIDHIDEOP            174
#define IDS_MSGUPDATEMACNAME            175
#define IDS_MSGKEYNOTBOUND              176
#define IDS_MSGRECOVER                  177
#define IDS_MSGNTIMESFOUND              178
#define IDS_WINDOWLIST                  179
#define IDS_SELECTCOMPILEWINDOW         180
#define IDS_TT_REGULAR_EXPRESSION       181
#define IDS_TT_PRESERVE_CASE            182
#define IDS_FILE_MODIFIED               183
#define IDS_FILE_READONLY               184
#define IDS_STATUSLINE                  186
#define IDS_NO_MACROS_DEFINED           190
#define IDS_ENTER_PASSWORD_TO_ENCRYPT   191
#define IDS_ENTER_PASSWORD_TO_DECRYPT   192
#define IDS_INSERT                      193
#define IDS_CREATE_BUFFER               195
#define IDM_UNDO                        210
#define IDM_DOAGAIN                     211
#define IDM_ERASEBLOCK                  212
#define IDM_REDO                        213
#define DLGFINDINFILES                  535
#define IDC_CUSTOM2                     1002
#define IDC_CHECK_ENCRYPT               1003
#define IDC_DOCTYPES                    1004
#define IDS_COMMAND251                  2299
#define IDS_COMMAND252                  2300
#define IDS_COMMAND253                  2301
#define IDS_COMMAND254                  2302

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        199
#define _APS_NEXT_COMMAND_VALUE         40008
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
