/*
 * BINOP.H
 *
 * PROJEKT: PKS-EDIT for ATARI - GEM
 *
 * purpose: binary operations
 *
 * 										created      : 
 * 										last modified:
 *										author	   : TOM
 *
 * (c) Pahlen & Krauﬂ
 */

# ifndef BINOP_H

# define	BIN_ADD			'+'
# define	BIN_AND			'&'
# define	BIN_OR			'|'
# define	BIN_MUL			'*'
# define	BIN_DIV			'/'
# define	BIN_MOD			'%'
# define	BIN_OR			'|'
# define	BIN_AND			'&'
# define	BIN_BRACKETS		'('
# define	BIN_SUB			'-'
# define	BIN_NOT			'~'
# define	BIN_XOR			'^'
# define	BIN_CONVERT		'C'

# define	BINOP_H
# endif
